ALTER TABLE skill_tree MODIFY description_content   varchar(400);
 
update skill_tree set description_content = concat(description_content,'<span>Computer Training Classes</span><span>Web Site Design Services </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Computer/Network Services';
update skill_tree set description_content = concat(description_content,'<span>Tools &amp; Industrial Equipment </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Product Assembly';
update skill_tree set description_content = concat(description_content,'<span>Media Centers </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Carpentry & Woodworking';
update skill_tree set description_content = concat(description_content,'<span>Refrigeration &amp; Ice Making</span><span> Heat Pumps </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Heating & Cooling';
update skill_tree set description_content = concat(description_content,'<span>Ceiling Fans,Light Switches</span><span> Doors</span><span> Disability Entrances</span><span> Whole House &amp; Attic Fans </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Handyman Services';
update skill_tree set description_content = concat(description_content,'<span>General Plumbing Repair &amp; Repiping</span><span> Clogged Drains</span><span> Hot Water Dispensers </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'General Plumbing & Bathrooms';
update skill_tree set description_content = concat(description_content,'<span>Stamping </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Floors & Patios';
update skill_tree set description_content = concat(description_content,'<span>Attic Fans (Roof-Mounted)  </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Roofing, Gutters, Windows & Siding';
update skill_tree set description_content = concat(description_content,'<span>Driveway/Walkway Paving &amp; Resurfacing</span><span> Piers/Docks</span><span> Wheel Chair Lifts</span><span> Automated Gates </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Other Services';
update skill_tree set description_content = concat(description_content,'<span>Attic Pull-down Ladders </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Garage & Shed';
update skill_tree set description_content = concat(description_content,'<span>Home or Office Interiors</span><span>Ducts &amp; Vents</span><span>Exterior Power Washing &amp; Sandblasting</span><span>Fire &amp; Flood Restoration</span><span>Fireplace &amp; Chimney</span><span>Junk &amp; Debris Removal</span><span>Maid Services</span><span>Swimming Pools</span><span>Upholstery &amp; Flooring</span><span> Windows,Window Treatments &amp; Walls </span>') ,modified_by = 'Sabina',modified_date = now() where root = '1' and node_name = 'Cleaning Services';
