package com.newco.marketplace.dto.vo.ledger;

import java.io.Serializable;
import java.util.Date;

public class Account implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6744007235384748229L;

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.account_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Long account_id;
    
    private Long cardTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.owner_entity_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007c
     */
    private Long owner_entity_type_id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.owner_entity_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Long owner_entity_id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.bank_name
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private String bank_name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.country_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Long country_id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.account_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Long account_type_id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.account_status_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Long account_status_id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.card_holder_name
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private String account_holder_name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.routing_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private String routing_no;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.account_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private String account_no;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.created_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Date created_date;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.modified_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private Date modified_date;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column account_hdr.modified_by
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    private String modified_by;

    private String account_descr;
    
    private boolean active_ind;
    
    private boolean enabled_ind;
    
    private int reconciledInd;
    
    private int autoACHInd;
    private int saveAutoFundInd;
    
    private int fundingTypeId;
    
    //SL-20853
    private String maskedAccountNo;
    
    private Long creditCardToken;
    
    private String zipCode;
    /**
	 * @return the fundingTypeId
	 */
	public int getFundingTypeId() {
		return fundingTypeId;
	}

	/**
	 * @param fundingTypeId the fundingTypeId to set
	 */
	public void setFundingTypeId(int fundingTypeId) {
		this.fundingTypeId = fundingTypeId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.account_id
     *
     * @return the value of account_hdr.account_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getAccount_id() {
        return account_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.account_id
     *
     * @param account_id the value for account_hdr.account_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setAccount_id(Long account_id) {
        this.account_id = account_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.owner_entity_type_id
     *
     * @return the value of account_hdr.owner_entity_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getOwner_entity_type_id() {
        return owner_entity_type_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.owner_entity_type_id
     *
     * @param owner_entity_type_id the value for account_hdr.owner_entity_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setOwner_entity_type_id(Long owner_entity_type_id) {
        this.owner_entity_type_id = owner_entity_type_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.owner_entity_id
     *
     * @return the value of account_hdr.owner_entity_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getOwner_entity_id() {
        return owner_entity_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.owner_entity_id
     *
     * @param owner_entity_id the value for account_hdr.owner_entity_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setOwner_entity_id(Long owner_entity_id) {
        this.owner_entity_id = owner_entity_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.bank_name
     *
     * @return the value of account_hdr.bank_name
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public String getBank_name() {
        return bank_name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.bank_name
     *
     * @param bank_name the value for account_hdr.bank_name
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setBank_name(String bank_name) {
        this.bank_name = bank_name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.country_id
     *
     * @return the value of account_hdr.country_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getCountry_id() {
        return country_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.country_id
     *
     * @param country_id the value for account_hdr.country_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setCountry_id(Long country_id) {
        this.country_id = country_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.account_type_id
     *
     * @return the value of account_hdr.account_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getAccount_type_id() {
        return account_type_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.account_type_id
     *
     * @param account_type_id the value for account_hdr.account_type_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setAccount_type_id(Long account_type_id) {
        this.account_type_id = account_type_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.account_status_id
     *
     * @return the value of account_hdr.account_status_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Long getAccount_status_id() {
        return account_status_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.account_status_id
     *
     * @param account_status_id the value for account_hdr.account_status_id
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setAccount_status_id(Long account_status_id) {
        this.account_status_id = account_status_id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.routing_no
     *
     * @return the value of account_hdr.routing_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public String getRouting_no() {
        return routing_no;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.routing_no
     *
     * @param routing_no the value for account_hdr.routing_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setRouting_no(String routing_no) {
        this.routing_no = routing_no;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.account_no
     *
     * @return the value of account_hdr.account_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public String getAccount_no() {
        return account_no;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.account_no
     *
     * @param account_no the value for account_hdr.account_no
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setAccount_no(String account_no) {
        this.account_no = account_no;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.created_date
     *
     * @return the value of account_hdr.created_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Date getCreated_date() {
        return created_date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.created_date
     *
     * @param created_date the value for account_hdr.created_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setCreated_date(Date created_date) {
        this.created_date = created_date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.modified_date
     *
     * @return the value of account_hdr.modified_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public Date getModified_date() {
        return modified_date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.modified_date
     *
     * @param modified_date the value for account_hdr.modified_date
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setModified_date(Date modified_date) {
        this.modified_date = modified_date;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column account_hdr.modified_by
     *
     * @return the value of account_hdr.modified_by
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public String getModified_by() {
        return modified_by;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column account_hdr.modified_by
     *
     * @param modified_by the value for account_hdr.modified_by
     *
     * @abatorgenerated Fri Aug 17 14:37:34 CDT 2007
     */
    public void setModified_by(String modified_by) {
        this.modified_by = modified_by;
    }

	public String getAccount_descr() {
		return account_descr;
	}

	public void setAccount_descr(String account_descr) {
		this.account_descr = account_descr;
	}

	public boolean isActive_ind() {
		return active_ind;
	}

	public void setActive_ind(boolean active_ind) {
		this.active_ind = active_ind;
	}

	public boolean isEnabled_ind() {
		return enabled_ind;
	}

	public void setEnabled_ind(boolean enabled_ind) {
		this.enabled_ind = enabled_ind;
	}

	public int getReconciledInd() {
		return reconciledInd;
	}

	public void setReconciledInd(int reconciledInd) {
		this.reconciledInd = reconciledInd;
	}

	public Long getCardTypeId() {
		return cardTypeId;
	}

	public void setCardTypeId(Long cardTypeId) {
		this.cardTypeId = cardTypeId;
	}

	public String getAccount_holder_name() {
		return account_holder_name;
	}

	public void setAccount_holder_name(String account_holder_name) {
		this.account_holder_name = account_holder_name;
	}

	public int getAutoACHInd() {
		return autoACHInd;
	}

	public void setAutoACHInd(int autoACHInd) {
		this.autoACHInd = autoACHInd;
	}

	public int getSaveAutoFundInd() {
		return saveAutoFundInd;
	}

	public void setSaveAutoFundInd(int saveAutoFundInd) {
		this.saveAutoFundInd = saveAutoFundInd;
	}
		
	/**
	 * getAccountDescription.
	 * 
	 * @return String
	 */
	public String getAccountDescription() {

		return getAccount_descr();
	}

	/**
	 * getAccountHolderName.
	 * 
	 * @return String
	 */
	public String getAccountHolderName() {
		return getAccount_holder_name();
	}

	/**
	 * getAccountId.
	 * 
	 * @return Long
	 */
	public Long getAccountId() {
		return getAccount_id();
	}

	/**
	 * getAccountNumber.
	 * 
	 * @return String
	 */
	public String getAccountNumber() {
		return getAccount_no();
	}

	/**
	 * getAccountStatusId.
	 * 
	 * @return Long
	 */
	public Long getAccountStatusId() {
		return getAccount_status_id();
	}

	/**
	 * getAccountTypeId.
	 * 
	 * @return Long
	 */
	public Long getAccountTypeId() {
		return getAccount_type_id();
	}

	/**
	 * getBankName.
	 * 
	 * @return String
	 */
	public String getBankName() {
		return getBank_name();
	}


	/**
	 * getCountryId.
	 * 
	 * @return Long
	 */
	public Long getCountryId() {
		return getCountry_id();
	}

	/**
	 * getCreatedDate.
	 * 
	 * @return Date
	 */
	public Date getCreatedDate() {
		return getCreated_date();
	}

	/**
	 * getModifiedBy.
	 * 
	 * @return String
	 */
	public String getModifiedBy() {
		return getModified_by();
	}

	/**
	 * getModifiedDate.
	 * 
	 * @return Date
	 */
	public Date getModifiedDate() {
		return getModified_date();
	}

	/**
	 * getOwnerEntityId.
	 * 
	 * @return Long
	 */
	public Long getOwnerEntityId() {
		return getOwner_entity_id();
	}

	/**
	 * getOwnerEntityTypeId.
	 * 
	 * @return Long
	 */
	public Long getOwnerEntityTypeId() {
		return getOwner_entity_type_id();
	}

	/**
	 * getRoutingNumber.
	 * 
	 * @return String
	 */
	public String getRoutingNumber() {
		return getRouting_no();
	}

	/**
	 * isActiveInd.
	 * 
	 * @return boolean
	 */
	public boolean isActiveInd() {
		return isActive_ind();
	}

	/**
	 * isEnabledInd.
	 * 
	 * @return boolean
	 */
	public boolean isEnabledInd() {
		return isEnabled_ind();
	}

	/**
	 * isEnabledInd.
	 * 
	 * @return boolean
	 */
	public boolean getEnabledInd() {
		return isEnabled_ind();
	}
	
	/**
	 * setAccountDescription.
	 * 
	 * @param accountDescription 
	 * 
	 * @return void
	 */
	public void setAccountDescription(String accountDescription) {
		setAccount_descr(accountDescription);
	}

	/**
	 * setAccountHolderName.
	 * 
	 * @param accountHolderName 
	 * 
	 * @return void
	 */
	public void setAccountHolderName(String accountHolderName) {
		setAccount_holder_name(accountHolderName);
	}

	/**
	 * setAccountId.
	 * 
	 * @param accountId 
	 * 
	 * @return void
	 */
	public void setAccountId(Long accountId) {
		setAccount_id(accountId);
	}

	/**
	 * setAccountNumber.
	 * 
	 * @param accountNumber 
	 * 
	 * @return void
	 */
	public void setAccountNumber(String accountNumber) {
		setAccountNo(accountNumber);
	}

	/**
	 * setAccountStatusId.
	 * 
	 * @param accountStatusId 
	 * 
	 * @return void
	 */
	public void setAccountStatusId(Long accountStatusId) {
		setAccount_status_id(accountStatusId);
	}

	/**
	 * setAccountTypeId.
	 * 
	 * @param accountTypeId 
	 * 
	 * @return void
	 */
	public void setAccountTypeId(Long accountTypeId) {
		setAccount_type_id(accountTypeId);
	}


	/**
	 * setBankName.
	 * 
	 * @param bankName 
	 * 
	 * @return void
	 */
	public void setBankName(String bankName) {
		setBank_name(bankName);
	}


	/**
	 * setCountryId.
	 * 
	 * @param countryId 
	 * 
	 * @return void
	 */
	public void setCountryId(Long countryId) {
		setCountry_id(countryId);
	}

	/**
	 * setCreatedDate.
	 * 
	 * @param createdDate 
	 * 
	 * @return void
	 */
	public void setCreatedDate(Date createdDate) {
		setCreated_date(createdDate);
	}

	/**
	 * setEnabledInd.
	 * 
	 * @param enabledInd 
	 * 
	 * @return void
	 */
	public void setEnabledInd(boolean enabledInd) {
		setEnabled_ind(enabledInd);
	}

	

	/**
	 * setModifiedBy.
	 * 
	 * @param modifiedBy 
	 * 
	 * @return void
	 */
	public void setModifiedBy(String modifiedBy) {
		setModified_by(modifiedBy);
	}

	/**
	 * setModifiedDate.
	 * 
	 * @param modifiedDate 
	 * 
	 * @return void
	 */
	public void setModifiedDate(Date modifiedDate) {

		setModified_date(modifiedDate);
	}

	/**
	 * setOwnerEntityId.
	 * 
	 * @param ownerEntityId 
	 * 
	 * @return void
	 */
	public void setOwnerEntityId(Long ownerEntityId) {
		setOwner_entity_id(ownerEntityId);
	}

	/**
	 * setOwnerEntityTypeId.
	 * 
	 * @param ownerEntityTypeId 
	 * 
	 * @return void
	 */
	public void setOwnerEntityTypeId(Long ownerEntityTypeId) {
		setOwner_entity_type_id(ownerEntityTypeId);
	}

	/**
	 * setRoutingNumber.
	 * 
	 * @param routingNumber 
	 * 
	 * @return void
	 */
	public void setRoutingNumber(String routingNumber) {
		setRouting_no(routingNumber);
	}

	public String getAccountNo() {
        return getAccount_no();
    }

     public void setAccountNo(String account_no) {
        setAccount_no(account_no);
    }
 	/**
 	 * setActiveInd.
 	 * 
 	 * @param activeInd 
 	 * 
 	 * @return void
 	 */
 	public void setActiveInd(boolean activeInd) {
 		setActive_ind(activeInd);
 	}
    
 	//SL-20853
 	/**
 	 * Gets the masked Account Number
 	 * @return
 	 */
	public String getMaskedAccountNo() {
		return maskedAccountNo;
	}
    
	/**
	 * sets the masked Account number
	 * @param maskedAccountNo
	 */
	public void setMaskedAccountNo(String maskedAccountNo) {
		this.maskedAccountNo = maskedAccountNo;
	}

	public Long getCreditCardToken() {
		return creditCardToken;
	}

	public void setCreditCardToken(Long creditCardToken) {
		this.creditCardToken = creditCardToken;
	}

	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	
	

}