/**
 * MarketServiceBus_Mapforce_CodeApplication.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.servicelive.esb.mapforce;

import javax.swing.UIManager;
import java.awt.*;


public class MarketServiceBus_Mapforce_CodeApplication {
	boolean packFrame = false;

	public MarketServiceBus_Mapforce_CodeApplication() {
		MarketServiceBus_Mapforce_CodeFrame frame = new MarketServiceBus_Mapforce_CodeFrame();
		if (packFrame)
			frame.pack();
		else
			frame.validate();

		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
		Dimension frameSize = frame.getSize();
		if (frameSize.height > screenSize.height)
			frameSize.height = screenSize.height;
		if (frameSize.width > screenSize.width)
			frameSize.width = screenSize.width;
		frame.setLocation( (screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
		frame.setVisible(true);
	}

	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			e.printStackTrace();
		}
		new MarketServiceBus_Mapforce_CodeApplication();
	}
}
