package com.newco.marketplace.webservices.dao;
// default package

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * AbstractShcNPSProcessLog generated by MyEclipse Persistence Tools
 */
@MappedSuperclass

public abstract class AbstractShcNPSProcessLog  implements java.io.Serializable {


    // Fields    

     private Integer npsProcessId;
     private String fileName;
     private Date createdDate;
     private Date modifiedDate;
     private String modifiedBy;


    // Constructors

    /** default constructor */
    public AbstractShcNPSProcessLog() {
    	// intentionally blank
    }

	/** minimal constructor */
    public AbstractShcNPSProcessLog(Integer npsProcessId, String fileName) {
        this.npsProcessId = npsProcessId;
        this.fileName = fileName;
    }
    
    /** full constructor */
    public AbstractShcNPSProcessLog(Integer npsProcessId, String fileName, Date createdDate, Date modifiedDate, String modifiedBy) {
        this.npsProcessId = npsProcessId;
        this.fileName = fileName;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.modifiedBy = modifiedBy;
    }

   
    // Property accessors
    @Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="nps_process_id", unique=true, nullable=false, insertable=true, updatable=true) 

    public Integer getNpsProcessId() {
        return this.npsProcessId;
    }
    
    public void setNpsProcessId(Integer npsProcessId) {
        this.npsProcessId = npsProcessId;
    }
    
    @Column(name="file_name", unique=false, nullable=false, insertable=true, updatable=true, length=75)

    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
@Temporal(TemporalType.DATE)
    @Column(name="created_date", unique=false, nullable=true, insertable=true, updatable=true, length=19)

    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
@Temporal(TemporalType.DATE)
    @Column(name="modified_date", unique=false, nullable=true, insertable=true, updatable=true, length=19)

    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    @Column(name="modified_by", unique=false, nullable=true, insertable=true, updatable=true, length=50)

    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
   








}