package com.newco.marketplace.webservices.dao;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * ShcNPSProcessLog generated by MyEclipse Persistence Tools
 */
@Entity
@Table(name="shc_nps_process_log", uniqueConstraints = {  }
)
public class ShcNPSProcessLog extends AbstractShcNPSProcessLog implements java.io.Serializable {

	private static final long serialVersionUID = -2962935202422785206L;

	/** default constructor */
    public ShcNPSProcessLog() {
    	// intentionally blank
    }

	/** minimal constructor */
    public ShcNPSProcessLog(Integer npsProcessId, String fileName) {
        super(npsProcessId, fileName);        
    }
    
    /** full constructor */
    public ShcNPSProcessLog(Integer npsProcessId, String fileName, Date createdDate, Date modifiedDate, String modifiedBy) {
        super(npsProcessId, fileName, createdDate, modifiedDate, modifiedBy);        
    }
   
}
