////////////////////////////////////////////////////////////////////////
//
// EDISemanticValidator.java
//
// This file was generated by MapForce 2011sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text.edi;

import java.util.HashMap;

import com.altova.CoreTypes;

public class EDISemanticValidator
{
	public static class X12Codes
	{
	    public static String[] AuthorizationInformationQualifiers =
	    {
		    "00",
		    "01",
		    "02",
		    "03",
		    "04",
		    "05"
	    };

	    public static String[] SecurityInformationQualifiers =
	    {
		    "00",
		    "01"
	    };

	    public static String[] InterchangeIDQualifiers =
	    {
		    "01",
		    "02",
		    "03",
		    "04",
		    "08",
		    "09",
		    "11",
		    "12",
		    "13",
		    "14",
		    "15",
		    "16",
		    "17",
		    "18",
		    "19",
		    "20",
		    "21",
		    "22",
		    "23",
		    "24",
		    "25",
		    "NR",
		    "ZZ"
	    };

	    public static String[] BooleanValues =
	    {
		    "0",
		    "1"
	    };

	    public static String[] InterchangeUsageIndicators =
	    {
		    "P",
		    "T",
		    "I"
	    };
	}

	private long mnSegmentCount;
	private long mnGroupCount;
	private long mnMessageCount;
	private EDISettings mSettings;
	HashMap<String, String> mMapEquality =
		new HashMap<String, String>();
	String msCurrentSegment;

	public EDISemanticValidator(EDISettings settings)
	{
		mSettings = settings;
		mnSegmentCount = 0;
		mnGroupCount = 0;
		mnMessageCount = 0;
	}

	public String validate ( String sField, String sValue )
	{
		switch( mSettings.getStandard())
		{
		case EDISettings.EDIFact: return validateEDIFACT( sField, sValue );
		case EDISettings.EDIX12: return validateX12( sField, sValue );
		case EDISettings.EDIHL7: return validateHL7( sField, sValue );
		}

		return "";
	}

	public void segment( String sSegment )
	{
		if (sSegment.equals("UNG") || sSegment.equals("GS") )
		{
			mnGroupCount++;
			mnMessageCount = 0;
		}

		else if ( sSegment.equals("UNH") || sSegment.equals("ST") )
		{
			mnMessageCount++;
			mnSegmentCount = 1;
		}

		else
			mnSegmentCount++;

		msCurrentSegment = sSegment;
	}

	private String validateX12( String sField, String sValue )
	{
		StringBuffer sError = new StringBuffer();
		String sExpectedValue;

		if ( sField.equals("F96") ) // Segment count in group
		{
			long nValue = CoreTypes.castToInt( sValue );
			if ( nValue != mnSegmentCount )
			{
				sError.append( "Field does not contain the correct number of segments (field value = ");
				sError.append( sValue);
                sError.append( ", counted ");
                sError.append( mnSegmentCount);
                sError.append( " ).");
			}
		}

		else if ( sField.equals( "F97") ) // Message count in group
		{
			if ( msCurrentSegment.equals("GE") )
			{
				long nValue = CoreTypes.castToInt( sValue );
				if ( nValue != mnMessageCount )
				{
					sError.append( "Field does not contain the correct number of messages (field value = ");
					sError.append( sValue);
                    sError.append( ", counted ");
                    sError.append(mnMessageCount);
                    sError.append( " ).");
				}
			}
		}

		else if ( sField.equals("F28") )
		{
			if ( msCurrentSegment.equals("GS") || msCurrentSegment.equals("GE") )
			{
				sExpectedValue = validateEquality( sField, sValue );
				if ( !sExpectedValue.equals("") )
				{
					sError.append("Field does not contain the same value as Interchange/Group/GS/F28 ('");
					sError.append( sValue);
					sError.append("' instead of '");
					sError.append(sExpectedValue);
					sError.append("').");
				}
			}
		}

		else if ( sField.equals("F329") )
		{
			if ( msCurrentSegment.equals("ST") || msCurrentSegment.equals("SE") )
			{
				sExpectedValue = validateEquality( sField, sValue );
				if ( !sExpectedValue.equals("") )
                {
					sError.append( "Field does not contain the same value as Interchange/Group/Message/ST/F329 ('");
					sError.append( sValue);
					sError.append( "' instead of '");
					sError.append( sExpectedValue);
					sError.append("').");
                }
			}
		}

		else if ( sField.equals( "F143") ) // message type
		{
			if ( msCurrentSegment.equals("ST") )
				if ( !sValue.equals(mSettings.getMessageType()) )
				{
					sError.append("'");
					sError.append(sValue);
					sError.append("' is not a correct message type specifier.");
				}
		}


		else if ( sField.equals("FI16") ) // Group count in interchange
		{
	        long nValue = CoreTypes.castToInt( sValue );
			if ( nValue != mnGroupCount )
			{
                sError.append("Field does not contain the correct number of function groups (field value = ");
                sError.append( sValue);
                sError.append(", counted ");
                sError.append( mnGroupCount);
                sError.append(" ).");
			}
		}

		else if ( sField.equals("FI01")  && msCurrentSegment.equals("ISA") )
			return validateX12Code( sField, sValue,
				X12Codes.AuthorizationInformationQualifiers );

		else if ( sField.equals("FI03") && msCurrentSegment.equals("ISA") )
			return validateX12Code( sField, sValue,
				X12Codes.SecurityInformationQualifiers );

		else if ( sField.equals("FI05") && msCurrentSegment.equals("ISA") )
			return validateX12Code( sField, sValue,
				X12Codes.InterchangeIDQualifiers);

		else if ( sField.equals("FI13") && msCurrentSegment.equals("ISA") )
			return validateX12Code( sField, sValue,
				X12Codes.BooleanValues);

		else if ( sField.equals("FI14") && msCurrentSegment.equals("ISA") )
			return validateX12Code( sField, sValue,
				X12Codes.InterchangeUsageIndicators);

		else if ( sField.equals("FI12") && ( msCurrentSegment.equals("ISA") || msCurrentSegment.equals("IEA") ) )
		{
			sExpectedValue = validateEquality( sField, sValue );
			if ( !sExpectedValue.equals("") )
			{
				sError.append("Field does not contain the same value as Interchange/Group/Message/ISA/FI12 ('");
				sError.append("' instead of '");
				sError.append( sExpectedValue);
				sError.append("').");
			}
		}

		return sError.toString();
	}

    private String validateX12Code( String sField, String sValue, String[] apcLegalValues )
    {
        boolean bLegalFound = false;

        int i;
        for ( i = 0; (i < apcLegalValues.length) && ( !bLegalFound); ++i )
        {
	        if ( sValue.equals(apcLegalValues[ i ]) )
		        bLegalFound = true;
        }
        if ( bLegalFound ) return "";

        StringBuffer ssItemList = new StringBuffer();
        for ( i = 0;  i < apcLegalValues.length - 1; ++i )
        {
	        ssItemList.append("'");
	        ssItemList.append("', ");
	        ssItemList.append(apcLegalValues[ i ]);
        }
        ssItemList.append("'");
        ssItemList.append( apcLegalValues[ apcLegalValues.length - 1 ]);
        ssItemList.append("'");

        String sMessage = sValue;
        sMessage += " is not a legal value. Legal values are: " + ssItemList.toString() + ".";
        return sMessage;
    }

	private String validateEDIFACT( String sField, String sValue )
	{
		StringBuffer sError = new StringBuffer();
		String sExpectedValue;

        if ( sField.equals("F0074") && msCurrentSegment.equals( "UNT") ) // segment count in message
        {
            long nValue = CoreTypes.castToInt( sValue );
	        if ( nValue != mnSegmentCount )
	        {
		        sError.append("Field does not contain the correct number of segments (field value = ");
				sError.append( sValue);
		        sError.append(", counted ");
		        sError.append( mnSegmentCount);
		        sError.append(" ).");
	        }
        }

        if ( sField.equals("F0060") && msCurrentSegment.equals( "UNE") ) // message count in group
        {
            long nValue = CoreTypes.castToInt( sValue );
	        if ( nValue != mnMessageCount )
	        {
		        sError.append( "Field does not contain the correct number of messages (field value = ");
		        sError.append( sValue);
		        sError.append(", counted ");
		        sError.append( mnMessageCount);
		        sError.append(" ).");
	        }
        }

        if ( sField.equals("F0036") && msCurrentSegment.equals( "UNZ") ) // message or group count in interchange
        {
	        // if we have at least one group, we count groups, otherwise messages
	        if ( mnGroupCount > 0) // count groups
	        {
                long nValue = CoreTypes.castToInt( sValue );
		        if ( nValue != mnGroupCount )
		        {
			        sError.append( "Field does not contain the correct number of function group (field value = ");
			        sError.append( sValue);
			        sError.append(", counted ");
			        sError.append( mnGroupCount);
			        sError.append(" ).");
		        }
	        }
	        else // count messages
	        {
                long nValue = CoreTypes.castToInt( sValue );
		        if ( nValue != mnMessageCount )
		        {
			        sError.append( "Field does not contain the correct number of messages (field value = ");
			        sError.append( sValue);
			        sError.append( ", counted ");
			        sError.append( mnMessageCount);
			        sError.append(" ).");
		        }
	        }
        }

        else if ( sField.equals("F0062") && ( msCurrentSegment.equals("UNH") || msCurrentSegment.equals( "UNT") ) ) // message reference number
        {
	        sExpectedValue = validateEquality( sField, sValue );
	        if ( !sExpectedValue.equals( "") )
	        {
		        sError.append( "Field does not contain the same value as Interchange/Group/Message/UNH/F0062 ('");
		        sError.append( sValue);
		        sError.append( "' instead of '");
		        sError.append( sExpectedValue);
		        sError.append( "').");
	        }
        }

        else if ( sField.equals("F0020") & ( msCurrentSegment.equals("UNZ") || msCurrentSegment.equals( "UNB") ) ) // interchange reference number
        {
	        sExpectedValue = validateEquality( sField, sValue );
	        if ( !sExpectedValue.equals( "") )
	        {
                sError.append( "Field does not contain the same value as Interchange/UNB/F0020 ('");
                sError.append( sValue);
                sError.append( "' instead of '");
                sError.append( sExpectedValue);
                sError.append( "').");
	        }
        }

        else if ( sField.equals("F0048") ) // group reference number
        {
	        sExpectedValue = validateEquality( sField, sValue );
	        if ( !sExpectedValue.equals( "") )
	        {
		        sError.append( "Field does not contain the same value as Interchange/Group/UNG/F0048 ('");
		        sError.append( sValue);
		        sError.append( "' instead of '");
		        sError.append( sExpectedValue);
		        sError.append( "').");
	        }
        }

        else if ( sField.equals("F0052") ) // version
        {
	        if (!sValue.equals(mSettings.getVersion()) )
	        {
		        sError.append( "Field value '");
		        sError.append( sValue);
		        sError.append( "' does not match expected message version number ('");
		        sError.append( mSettings.getVersion());
		        sError.append( "')");
	        }
        }

        else if ( sField.equals("F0054") ) // release
        {
	        if (!sValue.equals(mSettings.getRelease()) )
	        {
		        sError.append( "Field value '");
		        sError.append( sValue);
		        sError.append( "' does not match expected release number ('");
		        sError.append( mSettings.getRelease());
		        sError.append( "')");
	        }
        }

/*        else if ( sField.equals("F0051") ) // agency
        {
	        if (!sValue.equals(mSettings.getControllingAgency()) )
	        {
		        sError.append( "Field value '");
		        sError.append( sValue);
		        sError.append( "' does not match expected control agency code ('");
		        sError.append( mSettings.getControllingAgency());
		        sError.append( "')");
	        }
        }
*/
        else if ( sField.equals("F0065") && msCurrentSegment.equals( "UNH") ) // message type
        {
	        if ( !sValue.equals(mSettings.getMessageType()) )
		    {
	        	sError.append( "'");
	        	sError.append( sValue);
	        	sError.append("' is not a correct message type specifier.");
		    }
        }

        else if ( sField.equals("F0017") ) // date
        {
	        if ( !EDIDateTimeHelpers.IsDateCorrect( sValue ) )
	        {
		        sError.append( "'");
		        sError.append( sValue);
		        sError.append( "' is not an EDI formatted date value.");
	        }
        }

        else if ( sField.equals("F0019") ) // time
        {
	        if ( !EDIDateTimeHelpers.IsTimeCorrect( sValue ) )
	        {
		        sError.append( "'");
		        sError.append( sValue);
		        sError.append( "' is not an EDI formatted time value.");
	        }
        }

        return sError.toString();
	}

	private String validateHL7( String sField, String sValue )
	{

		return "";
	}

    String validateEquality( String sField, String sValue )
    {
        // if has no field, add it; if map has field compare it and remove it
        if (!mMapEquality.containsKey(sField)) // map has no field?
        {
            mMapEquality.put(sField, sValue);
	        return "";
        }

        // obviously map has the field
        String ret = "";
        if ( !mMapEquality.get(sField).equals(sValue))
            ret = (String)mMapEquality.get(sField);
        mMapEquality.remove(sField);
        return ret;
    }
}
