insert into `application_properties`(`app_key`,`app_value`,`app_desc`,`created_date`,`modified_date`,`modified_by`) 
values ('ptd_time_of_run','5','This time will form the side of a select for ptd records in SLDB (i.e. where date is between ptd_time_of_run and (ptd_time_of_run - 24))',now(),now(),null);

DROP TABLE `ptd_file_transactions`;
CREATE TABLE `ptd_file_transactions` (
  `ptd_transaction_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `fullfillment_entry_id` int(11) DEFAULT NULL,
  `v1_account_number` bigint(11) DEFAULT NULL,
  `ptd_request_code` varchar(50) DEFAULT NULL,
  `ptd_response_code` varchar(50) DEFAULT NULL,
  `ptd_reversal_flag` varchar(50) DEFAULT NULL,
  `trans_amount` double(12,2) DEFAULT NULL,
  `entry_type_id` varchar(2) DEFAULT NULL,
  `created_date` timestamp NULL DEFAULT NULL,
  `updated_date` timestamp NULL DEFAULT NULL,
  `email_sent_flag` varchar(10) DEFAULT NULL,
  `ptd_log_id` int(10) UNSIGNED DEFAULT NULL,
  `entry_date` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `record_form_indicator` INT(1) UNSIGNED,
	`reserved_1` INT(4) UNSIGNED,
	`reserved_2` INT(5) UNSIGNED,
	`merchant_id` BIGINT(11) UNSIGNED,
	`reserved_3` INT(4) UNSIGNED,
	`reserved_4` INT(5) UNSIGNED,
	`alternate_merchant_number` BIGINT(11) UNSIGNED,
	`terminal_id` INT(4) UNSIGNED,
	`terminal_transaction_number` BIGINT(17) UNSIGNED,
	`base_amount` BIGINT(12) UNSIGNED,
	`reporting_amount` BIGINT(12) UNSIGNED,
	`base_currency_code` INT(3) UNSIGNED,
	`local_currency_code` INT(3) UNSIGNED,
	`reporting_currency_code` INT(3) UNSIGNED,
	`exchange_code` BIGINT(14) UNSIGNED,
	`clerk_id` VARCHAR(8),
	`balance_sign` VARCHAR(1),
	`base_balance` BIGINT(12) UNSIGNED,
	`consortium_code` INT(8) UNSIGNED,
	`promotion_code` INT(8) UNSIGNED,
	`fdms_local_timestamp` BIGINT(13) UNSIGNED,
	`terminal_local_timestamp` BIGINT(13) UNSIGNED,
	`replaced_by_account_number` BIGINT(19) UNSIGNED,
	`reserved_5` VARCHAR(8),
	`user_id` VARCHAR(8),
	`card_class` INT(4) UNSIGNED,
	`expiration_date` INT(7) UNSIGNED,
	`card_cost` BIGINT(12) UNSIGNED,
	`escheatable_transaction` VARCHAR(1),
	`reference_number` VARCHAR(16),
	`user_2` VARCHAR(20),
	`local_cash_back` BIGINT(12) UNSIGNED,
	`base_cash_back` BIGINT(12) UNSIGNED,
	`reporting_cash_back` BIGINT(12) UNSIGNED,
	`local_lock_amount` BIGINT(12) UNSIGNED,
	`base_lock_amount` BIGINT(12) UNSIGNED,
	`reversed_timestamp` BIGINT(13) UNSIGNED,
	`processed_date` BIGINT(13) UNSIGNED,
	`original_request_code` INT(5) UNSIGNED,
	`internal_request_code` INT(5) UNSIGNED,
	`call_trace_info` VARCHAR(40),
	`uplift_amount` BIGINT(12) UNSIGNED,
	`gmt_timestamp` VARCHAR(13),
	`alternate_account_number` BIGINT(19) UNSIGNED,
  PRIMARY KEY  (`ptd_transaction_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
