INSERT INTO spnet_email_template(template_id, created_date, modified_date, eid, priority, template_from, template_name, template_source, template_subject, template_to, wf_entity_state) 
    VALUES(3, '2008-12-16 1:40:29', '2008-12-16 1:40:29', 51903, 1, 'noreply@servicelive.com', 'InvitedToSpn', 
    '<html><head><style type="text/css">	#email_body {		font-family: Arial;		color: #505050;		font-size: 8.5pt;		font-weight: normal;		font-style: normal;		text-align: left;		background-color: #FFFFFF;	}</style></head><body><img src="cid:SL_LOGO"><br/><br/><div id="email_body">Dear ${providerFirmAdminName},<br/><br/>You are invited to join an ${spnName}, a select provider network (SPN) for ${spnCompanyName} at ServiceLive.   To learn more and how to become a member, <a href="${serviceLiveUrl}">log in to ServiceLive</a> and click on the link in your "Communication Monitor" for this SPN.<br/><br/>Here you will find the details about this great opportunity for your business, including:<ul><li>Instructions to join,</li><li>Information about ${spnCompanyName},</li><li>Credentials and criteria required for membership for your company and provider team,</li><li>And any documents necessary to complete your application.</li></ul>This offer does expire. Take the time now to see if this is right for your company''s future.<br/>If you have any questions about the ${spnName}, please contact: ${spnContactName} at ${spnContactPhone}.<br/><br/>Regards<br/><br/>${spnContactName} <br/><br/>${spnCompanyName}<br/>${spnContactPhone}<br/>${spnContactEmail}<br/></div></body></html>',
    'You are invited to join ${spnName}', 
    'himanshu@servicelive.com;suketu@servicelive.com;suganya@servicelive.com;', 
    'PF INVITED TO SPN');

insert into spnet_email_template (template_id, created_date, modified_date, eid, priority, template_from, template_name, template_source, template_subject, template_to, wf_entity_state) 
values(1,'2009-01-02 10:26:11','2008-12-18 10:26:11',51920,0,'noreply@servicelive.com','CampaignPending',
'<html><head><style type="text/css">	#email_body {		font-family: Arial;		color: #505050;		font-size: 8.5pt;		font-weight: normal;		font-style: normal;		text-align: left;		background-color: #FFFFFF;	}</style></head><body><img src="cid:SL_LOGO"><br/><br/><div id="email_body"><br><ul> <li>SPN Name: ${spnName}</li><li>Buyer : ${buyerName} (${buyerId})</li><li>Contact : ${spnContactName} <br /> ${spnContactEmail} <br /> ${spnContactPhone} </li><li>Campaign Name: ${campaignName}</li>${dynamicMessage}<li>Campaign Duration : ${campaignStartDate} to ${campaignEndDate}</li></ul><br/>Please login to ServiceLive to approve the campaign prior to ${campaignStartDate} for the SPN given above. Your approval is mandatory for sending the invitation emails to provider firms.<br/></div></body></html>',
'Approval request for SPN Campaign ${campaignName}',
'himanshu@servicelive.com;suketu@servicelive.com;suganya@servicelive.com;',
'CAMPAIGN PENDING');
