/**
 * vmf/vmf2_inputtoresult.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.servicelive.esb.mapforce.vmf;

import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import com.altova.db.*;
import com.altova.text.tablelike.*;
import com.altova.text.*;
import com.altova.text.edi.*;
import java.util.*;

public class vmf2_inputtoresult extends com.altova.TraceProvider 
{
	static class Main implements IEnumerable
	{
		java.math.BigInteger var1_input;
	
		public Main(java.math.BigInteger var1_input)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator enumerator() {return new MFEmptySequence().enumerator();}
				
	}


		

	private static java.util.HashMap hash = null;

	private synchronized static void init()
	{
		hash = new java.util.HashMap();
		hash.put(com.altova.CoreTypes.box(new java.math.BigInteger("4")), com.altova.CoreTypes.box(new java.math.BigInteger("1")));
	}


	public static IEnumerable create(java.math.BigInteger var1_input)
	{
		if (hash == null) init();
		Object o = hash.get(var1_input);
		if (o != null)
			return new MFSingletonSequence(o);
		else
			return new MFSingletonSequence(com.altova.CoreTypes.box(new java.math.BigInteger("3")));

	}


	static IEnumerable throwUserException(String content)
	{
		throw new com.altova.UserException(content);
	}
}
