/**
 * Command.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

 

package com.altova.db;

import com.altova.types.*;
import java.util.ArrayList;


public class Command {
	// members
	protected String	statement;
	protected ArrayList	parameters;
	protected boolean	isAutoReadFieldsIntoBuffer;

	public class FieldValue
	{
		public Object value = null;
		public int type = java.sql.Types.JAVA_OBJECT;
		public int length = -1;
		public int precision = -1;
		public int scale = -1;		
	}
	
	// construction
	public Command(String newStatement, boolean newIsAutoReadFieldsIntoBuffer) {
		statement = newStatement;
		isAutoReadFieldsIntoBuffer = newIsAutoReadFieldsIntoBuffer;
		parameters = new ArrayList();
	}

	// accessors
	public String getStatement() {
		return statement;
	}
			
	public void setStatement(String newValue) {
		statement = newValue;
	}

	public ArrayList getParameters() {
		return parameters;
	}

	public boolean isAutoReadFieldsIntoBuffer()	{
		return isAutoReadFieldsIntoBuffer;
	}

	public void setAutoReadFieldsIntoBuffer(boolean newValue) {
		isAutoReadFieldsIntoBuffer = newValue;
	}

	// methods
	public boolean isEmpty() {
		return statement.length() == 0;
	}

	public void addParameter(Object newValue)	{
		FieldValue fieldValue = new FieldValue();
		fieldValue.value = newValue;
		addParameter(fieldValue);
	}

	public void addParameter(Object newValue, int type, int length, int precision, int scale) {
		FieldValue fieldValue = new FieldValue();
		fieldValue.value = newValue;
		fieldValue.type = type;
		fieldValue.length = length;
		fieldValue.precision = precision;
		fieldValue.scale = scale;
		addParameter(fieldValue);
	}

	public void addParameter(FieldValue fieldValue )	{
		parameters.add(fieldValue);
	}

}
