/**
 * DbExecuteException.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package com.altova.db;


public class DbExecuteException extends DbException {
	// error-kind enumeration
	public static final int	PREPARE_COMMAND = 0;
	public static final int	PREPARE_PARAMS = 1;
	public static final int	EXECUTE = 2;
	public static final int	GET_AFFECTED = 3;
	public static final int	GET_COLUMN = 4;
	public static final int	SET_COLUMN = 5;
	public static final int	READ_NEXT_RESULT = 6;

	protected int	nErrorKind;

	// construction
	public DbExecuteException( int errorKind, String sqlStatement, String errorMessage ) {
		super( sqlStatement, errorMessage );
		nErrorKind = errorKind;
	}

	public DbExecuteException( DbExecuteException other ) {
		super( other.sFailedItem, other.sErrorMessage );
		nErrorKind = other.nErrorKind;
	}

	public DbExecuteException(Exception other) {
		super(other);
	}

	// accessors
	public int getErrorKind() {
		return nErrorKind;
	}

	public String getSQLStatement() {
		return sFailedItem;
	}
}
