/**
 * Record.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.altova.db;

import java.util.HashMap;
import com.altova.mapforce.IEnumerable;

public class Record extends HashMap<String, IEnumerable>
{
	private int col = 1;
	public int getCurrentColumn() { return col++; }
	public Record() {super();}
}
