////////////////////////////////////////////////////////////////////////
//
// AlwaysEmptyTextNodeList.java
//
// This file was generated by MapForce 2011sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text;

public class AlwaysEmptyTextNodeList extends TextNodeList {
	public AlwaysEmptyTextNodeList() {
		super(null);
	}

	public void add(ITextNode rhs) {
	} // no-op

	public void insertAt(ITextNode rhs, int index) {
	} // no-op

}
