////////////////////////////////////////////////////////////////////////
//
// TextNodeListIterator.java
//
// This file was generated by MapForce 2011sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.text;

import java.util.Iterator;

public class TextNodeListIterator implements Iterator {
	private Iterator m_InnerIterator = null;

	public boolean hasNext() {
		return m_InnerIterator.hasNext();
	}

	public Object next() {
		if( !m_InnerIterator.hasNext() ) return null;
		return m_InnerIterator.next();
	}

	public void remove() {
		m_InnerIterator.remove();
	}

	public TextNodeListIterator(Iterator inneriterator) {
		m_InnerIterator = inneriterator;
	}

	public TextNode nextTextNode() {
		return (TextNode) this.next();
	}
}
