/**
 * HSRNewRequestDocument.java
 *
 * This file was generated by MapForce 2011sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.servicelive.esb.mapforce.HSRNewRequest;

import java.io.IOException;

import com.altova.AltovaException;
import com.altova.text.TextNode;
import com.altova.text.flex.*;
import com.altova.text.TextNodeXMLSerializer;


public class HSRNewRequestDocument extends TextDocument {

	// Project Root2
	static private CommandProject command_Root2 = new CommandProject("Root", 0);

	// CSV CSV2
	static private CommandStore store_CSV2_Service_Unit_Num2 = new CommandStore("Service Unit Num", 0, "");
	static private CommandStore store_CSV2_Service_Order_Num2 = new CommandStore("Service Order Num", 0, "");
	static private CommandStore store_CSV2_Repair_Tag_Bar_Code2 = new CommandStore("Repair Tag Bar Code", 0, "");
	static private CommandStore store_CSV2_Order_Taken_Time2 = new CommandStore("Order Taken Time", 0, "");
	static private CommandStore store_CSV2_Order_Taken_Date2 = new CommandStore("Order Taken Date", 0, "");
	static private CommandStore store_CSV2_Promised_Date2 = new CommandStore("Promised Date", 0, "");
	static private CommandStore store_CSV2_Promised_Time_From2 = new CommandStore("Promised Time From", 0, "");
	static private CommandStore store_CSV2_Promised_Time_To2 = new CommandStore("Promised Time To", 0, "");
	static private CommandStore store_CSV2_Original_Scheduled_Date2 = new CommandStore("Original Scheduled Date", 0, "");
	static private CommandStore store_CSV2_Original_Time_From2 = new CommandStore("Original Time From", 0, "");
	static private CommandStore store_CSV2_Original_Time_To2 = new CommandStore("Original Time To", 0, "");
	static private CommandStore store_CSV2_Customer_Number2 = new CommandStore("Customer Number", 0, "");
	static private CommandStore store_CSV2_Customer_Type2 = new CommandStore("Customer Type", 0, "");
	static private CommandStore store_CSV2_Customer_First_Name2 = new CommandStore("Customer First Name", 0, "");
	static private CommandStore store_CSV2_Customer_Last_Name2 = new CommandStore("Customer Last Name", 0, "");
	static private CommandStore store_CSV2_Customer_Phone2 = new CommandStore("Customer Phone", 0, "");
	static private CommandStore store_CSV2_Customer_Alt_Phone2 = new CommandStore("Customer Alt Phone", 0, "");
	static private CommandStore store_CSV2_Customer_Preferred_Language2 = new CommandStore("Customer Preferred Language", 0, "");
	static private CommandStore store_CSV2_Business_Address_Ind2 = new CommandStore("Business Address Ind", 0, "");
	static private CommandStore store_CSV2_Repair_Address_12 = new CommandStore("Repair Address 1", 0, "");
	static private CommandStore store_CSV2_Repair_Address_22 = new CommandStore("Repair Address 2", 0, "");
	static private CommandStore store_CSV2_City2 = new CommandStore("City", 0, "");
	static private CommandStore store_CSV2_State2 = new CommandStore("State", 0, "");
	static private CommandStore store_CSV2_Postal_Code2 = new CommandStore("Postal Code", 0, "");
	static private CommandStore store_CSV2_Contact_Name2 = new CommandStore("Contact Name", 0, "");
	static private CommandStore store_CSV2_Payment_Method_Ind2 = new CommandStore("Payment Method Ind", 0, "");
	static private CommandStore store_CSV2_Customer_Charge_Account_Num2 = new CommandStore("Customer Charge Account Num", 0, "");
	static private CommandStore store_CSV2_Customer_Charge_Account_Exp2 = new CommandStore("Customer Charge Account Exp", 0, "");
	static private CommandStore store_CSV2_Service_Requested2 = new CommandStore("Service Requested", 0, "");
	static private CommandStore store_CSV2_Service_Order_Status_Code2 = new CommandStore("Service Order Status Code", 0, "");
	static private CommandStore store_CSV2_Service_Location_Code2 = new CommandStore("Service Location Code", 0, "");
	static private CommandStore store_CSV2_Special_Instructions_12 = new CommandStore("Special Instructions 1", 0, "");
	static private CommandStore store_CSV2_Special_Instructions_22 = new CommandStore("Special Instructions 2", 0, "");
	static private CommandStore store_CSV2_Permanent_Instructions2 = new CommandStore("Permanent Instructions", 0, "");
	static private CommandStore store_CSV2_Priority_Indicator2 = new CommandStore("Priority Indicator", 0, "");
	static private CommandStore store_CSV2_Last_Modified_by_Employee_ID2 = new CommandStore("Last Modified by Employee ID", 0, "");
	static private CommandStore store_CSV2_Coverage_Type_Labor2 = new CommandStore("Coverage Type Labor", 0, "");
	static private CommandStore store_CSV2_Coverage_Type_Parts2 = new CommandStore("Coverage Type Parts", 0, "");
	static private CommandStore store_CSV2_Exception_Part_Warranty_Exp3 = new CommandStore("Exception Part Warranty Exp", 0, "");
	static private CommandStore store_CSV2_PA_Agreement_Num2 = new CommandStore("PA Agreement Num", 0, "");
	static private CommandStore store_CSV2_Division2 = new CommandStore("Division", 0, "");
	static private CommandStore store_CSV2_Protection_Agreement_Type2 = new CommandStore("Protection Agreement Type", 0, "");
	static private CommandStore store_CSV2_Protection_Agreement_Latest_Exp2 = new CommandStore("Protection Agreement Latest Exp", 0, "");
	static private CommandStore store_CSV2_Protection_Agreement_Plan_Type2 = new CommandStore("Protection Agreement Plan Type", 0, "");
	static private CommandStore store_CSV2_Merchandise_Code2 = new CommandStore("Merchandise Code", 0, "");
	static private CommandStore store_CSV2_Merchandise_Description2 = new CommandStore("Merchandise Description", 0, "");
	static private CommandStore store_CSV2_Purchase_Date2 = new CommandStore("Purchase Date", 0, "");
	static private CommandStore store_CSV2_Brand2 = new CommandStore("Brand", 0, "");
	static private CommandStore store_CSV2_Model2 = new CommandStore("Model", 0, "");
	static private CommandStore store_CSV2_Serial_Number2 = new CommandStore("Serial Number", 0, "");
	static private CommandStore store_CSV2_Sears_Sold_Code2 = new CommandStore("Sears Sold Code", 0, "");
	static private CommandStore store_CSV2_System_Item_Suffix2 = new CommandStore("System Item Suffix", 0, "");
	static private CommandStore store_CSV2_Item_Num2 = new CommandStore("Item Num", 0, "");
	static private CommandStore store_CSV2_Sears_Store_Num2 = new CommandStore("Sears Store Num", 0, "");
	static private CommandStore store_CSV2_Original_Delivery_Date2 = new CommandStore("Original Delivery Date", 0, "");
	static private CommandStore store_CSV2_Residential_or_Commercial_Usage2 = new CommandStore("Residential or Commercial Usage", 0, "");
	static private CommandStore store_CSV2_Promotion_Ind2 = new CommandStore("Promotion Ind", 0, "");
	static private CommandStore store_CSV2_Part_Warranty_Exp2 = new CommandStore("Part Warranty Exp", 0, "");
	static private CommandStore store_CSV2_Labor_Warranty_Exp2 = new CommandStore("Labor Warranty Exp", 0, "");
	static private CommandStore store_CSV2_Exception_Part_Warranty_Exp22 = new CommandStore("Exception Part Warranty Exp2", 0, "");
	static private CommandStore store_CSV2_Labor_Warranty2 = new CommandStore("Labor Warranty", 0, "");
	static private CommandStore store_CSV2_Repair_Instructions2 = new CommandStore("Repair Instructions", 0, "");
	static private CommandStore store_CSV2_Employee_Num_who_Created_SO2 = new CommandStore("Employee Num who Created SO", 0, "");
	static private CommandStore store_CSV2_Solicit_PA_Indicator2 = new CommandStore("Solicit PA Indicator", 0, "");
	static private CommandStore store_CSV2_Service_Order_Creation_Unit_Num2 = new CommandStore("Service Order Creation Unit Num", 0, "");
	static private CommandStore store_CSV2_Proc_ID2 = new CommandStore("Proc ID", 0, "");
	static private CommandStore store_CSV2_Contract_Num2 = new CommandStore("Contract Num", 0, "");
	static private CommandStore store_CSV2_Contract_Exp2 = new CommandStore("Contract Exp", 0, "");
	static private CommandStore store_CSV2_Authorization_Num2 = new CommandStore("Authorization Num", 0, "");
	static private CommandStore store_CSV2_Field702 = new CommandStore("Field70", 0, "");
	static private ColumnDelimited[] columns_CSV2 = {
		new ColumnDelimited(store_CSV2_Service_Unit_Num2, "Service Unit Num"),
		new ColumnDelimited(store_CSV2_Service_Order_Num2, "Service Order Num"),
		new ColumnDelimited(store_CSV2_Repair_Tag_Bar_Code2, "Repair Tag Bar Code"),
		new ColumnDelimited(store_CSV2_Order_Taken_Time2, "Order Taken Time"),
		new ColumnDelimited(store_CSV2_Order_Taken_Date2, "Order Taken Date"),
		new ColumnDelimited(store_CSV2_Promised_Date2, "Promised Date"),
		new ColumnDelimited(store_CSV2_Promised_Time_From2, "Promised Time From"),
		new ColumnDelimited(store_CSV2_Promised_Time_To2, "Promised Time To"),
		new ColumnDelimited(store_CSV2_Original_Scheduled_Date2, "Original Scheduled Date"),
		new ColumnDelimited(store_CSV2_Original_Time_From2, "Original Time From"),
		new ColumnDelimited(store_CSV2_Original_Time_To2, "Original Time To"),
		new ColumnDelimited(store_CSV2_Customer_Number2, "Customer Number"),
		new ColumnDelimited(store_CSV2_Customer_Type2, "Customer Type"),
		new ColumnDelimited(store_CSV2_Customer_First_Name2, "Customer First Name"),
		new ColumnDelimited(store_CSV2_Customer_Last_Name2, "Customer Last Name"),
		new ColumnDelimited(store_CSV2_Customer_Phone2, "Customer Phone"),
		new ColumnDelimited(store_CSV2_Customer_Alt_Phone2, "Customer Alt Phone"),
		new ColumnDelimited(store_CSV2_Customer_Preferred_Language2, "Customer Preferred Language"),
		new ColumnDelimited(store_CSV2_Business_Address_Ind2, "Business Address Ind"),
		new ColumnDelimited(store_CSV2_Repair_Address_12, "Repair Address 1"),
		new ColumnDelimited(store_CSV2_Repair_Address_22, "Repair Address 2"),
		new ColumnDelimited(store_CSV2_City2, "City"),
		new ColumnDelimited(store_CSV2_State2, "State"),
		new ColumnDelimited(store_CSV2_Postal_Code2, "Postal Code"),
		new ColumnDelimited(store_CSV2_Contact_Name2, "Contact Name"),
		new ColumnDelimited(store_CSV2_Payment_Method_Ind2, "Payment Method Ind"),
		new ColumnDelimited(store_CSV2_Customer_Charge_Account_Num2, "Customer Charge Account Num"),
		new ColumnDelimited(store_CSV2_Customer_Charge_Account_Exp2, "Customer Charge Account Exp"),
		new ColumnDelimited(store_CSV2_Service_Requested2, "Service Requested"),
		new ColumnDelimited(store_CSV2_Service_Order_Status_Code2, "Service Order Status Code"),
		new ColumnDelimited(store_CSV2_Service_Location_Code2, "Service Location Code"),
		new ColumnDelimited(store_CSV2_Special_Instructions_12, "Special Instructions 1"),
		new ColumnDelimited(store_CSV2_Special_Instructions_22, "Special Instructions 2"),
		new ColumnDelimited(store_CSV2_Permanent_Instructions2, "Permanent Instructions"),
		new ColumnDelimited(store_CSV2_Priority_Indicator2, "Priority Indicator"),
		new ColumnDelimited(store_CSV2_Last_Modified_by_Employee_ID2, "Last Modified by Employee ID"),
		new ColumnDelimited(store_CSV2_Coverage_Type_Labor2, "Coverage Type Labor"),
		new ColumnDelimited(store_CSV2_Coverage_Type_Parts2, "Coverage Type Parts"),
		new ColumnDelimited(store_CSV2_Exception_Part_Warranty_Exp3, "Exception Part Warranty Exp"),
		new ColumnDelimited(store_CSV2_PA_Agreement_Num2, "PA Agreement Num"),
		new ColumnDelimited(store_CSV2_Division2, "Division"),
		new ColumnDelimited(store_CSV2_Protection_Agreement_Type2, "Protection Agreement Type"),
		new ColumnDelimited(store_CSV2_Protection_Agreement_Latest_Exp2, "Protection Agreement Latest Exp"),
		new ColumnDelimited(store_CSV2_Protection_Agreement_Plan_Type2, "Protection Agreement Plan Type"),
		new ColumnDelimited(store_CSV2_Merchandise_Code2, "Merchandise Code"),
		new ColumnDelimited(store_CSV2_Merchandise_Description2, "Merchandise Description"),
		new ColumnDelimited(store_CSV2_Purchase_Date2, "Purchase Date"),
		new ColumnDelimited(store_CSV2_Brand2, "Brand"),
		new ColumnDelimited(store_CSV2_Model2, "Model"),
		new ColumnDelimited(store_CSV2_Serial_Number2, "Serial Number"),
		new ColumnDelimited(store_CSV2_Sears_Sold_Code2, "Sears Sold Code"),
		new ColumnDelimited(store_CSV2_System_Item_Suffix2, "System Item Suffix"),
		new ColumnDelimited(store_CSV2_Item_Num2, "Item Num"),
		new ColumnDelimited(store_CSV2_Sears_Store_Num2, "Sears Store Num"),
		new ColumnDelimited(store_CSV2_Original_Delivery_Date2, "Original Delivery Date"),
		new ColumnDelimited(store_CSV2_Residential_or_Commercial_Usage2, "Residential or Commercial Usage"),
		new ColumnDelimited(store_CSV2_Promotion_Ind2, "Promotion Ind"),
		new ColumnDelimited(store_CSV2_Part_Warranty_Exp2, "Part Warranty Exp"),
		new ColumnDelimited(store_CSV2_Labor_Warranty_Exp2, "Labor Warranty Exp"),
		new ColumnDelimited(store_CSV2_Exception_Part_Warranty_Exp22, "Exception Part Warranty Exp2"),
		new ColumnDelimited(store_CSV2_Labor_Warranty2, "Labor Warranty"),
		new ColumnDelimited(store_CSV2_Repair_Instructions2, "Repair Instructions"),
		new ColumnDelimited(store_CSV2_Employee_Num_who_Created_SO2, "Employee Num who Created SO"),
		new ColumnDelimited(store_CSV2_Solicit_PA_Indicator2, "Solicit PA Indicator"),
		new ColumnDelimited(store_CSV2_Service_Order_Creation_Unit_Num2, "Service Order Creation Unit Num"),
		new ColumnDelimited(store_CSV2_Proc_ID2, "Proc ID"),
		new ColumnDelimited(store_CSV2_Contract_Num2, "Contract Num"),
		new ColumnDelimited(store_CSV2_Contract_Exp2, "Contract Exp"),
		new ColumnDelimited(store_CSV2_Authorization_Num2, "Authorization Num"),
		new ColumnDelimited(store_CSV2_Field702, "Field70"),
};
	static private CommandCSV command_CSV2 = new CommandCSV("CSV", columns_CSV2, false, "\n", "|", '\"', '\0', true);

	public HSRNewRequestDocument()	{
		command_Root2.setNext(command_CSV2);

		rootCommand = command_Root2;
	}
}


