package com.servicelive.wallet.valuelink;

// TODO: Auto-generated Javadoc
/**
 * Class ValueLinkConstants.
 */
public class ValueLinkConstants {

	/* These values are the same as found in lu_iso_sl_message_template table */
	/** ACTIVATION_RELOAD_REQUEST. */
	public static final String ACTIVATION_RELOAD_REQUEST = "ACTIVATION_RELOAD_REQUEST";

	/** ACTIVATION_RELOAD_RESPONSE. */
	public static final String ACTIVATION_RELOAD_RESPONSE = "ACTIVATION_RELOAD_RESPONSE";

	/** BALANCE_ADJUSTMENT_REDEEM_REQUEST. */
	public static final String BALANCE_ADJUSTMENT_REDEEM_REQUEST = "BALANCE_ADJUSTMENT_REDEEM_REQUEST";

	/** BALANCE_ADJUSTMENT_REDEEM_RESPONSE. */
	public static final String BALANCE_ADJUSTMENT_REDEEM_RESPONSE = "BALANCE_ADJUSTMENT_REDEEM_RESPONSE";

	/** BALANCE_ADJUSTMENT_RELOAD_REQUEST. */
	public static final String BALANCE_ADJUSTMENT_RELOAD_REQUEST = "BALANCE_ADJUSTMENT_RELOAD_REQUEST";

	/** BALANCE_ADJUSTMENT_RELOAD_RESPONSE. */
	public static final String BALANCE_ADJUSTMENT_RELOAD_RESPONSE = "BALANCE_ADJUSTMENT_RELOAD_RESPONSE";

	/** BALANCE_ENQUIRY_REQUEST. */
	public static final String BALANCE_ENQUIRY_REQUEST = "BALANCE_ENQUIRY_REQUEST";

	/** BALANCE_ENQUIRY_RESPONSE. */
	public static final String BALANCE_ENQUIRY_RESPONSE = "BALANCE_ENQUIRY_RESPONSE";

	/** BALANCE_ENQUIRY_STAN. */
	public static final String BALANCE_ENQUIRY_STAN = "BAL_ENQ";

	/** DATA_TYPE_ALPHA. */
	public static final String DATA_TYPE_ALPHA = "A";

	/** DATA_TYPE_ALPHANUMERIC. */
	public static final String DATA_TYPE_ALPHANUMERIC = "AN";

	/** DATA_TYPE_ALPHANUMERIC_SPACEPAD. */
	public static final String DATA_TYPE_ALPHANUMERIC_SPACEPAD = "ANP";

	/** DATA_TYPE_ALPHANUMERIC_SPECIALCHARS. */
	public static final String DATA_TYPE_ALPHANUMERIC_SPECIALCHARS = "ANS";

	/** DATA_TYPE_NUMERIC. */
	public static final String DATA_TYPE_NUMERIC = "N";

	/** DATA_TYPE_NUMERIC_SPECIALCHARS. */
	public static final String DATA_TYPE_NUMERIC_SPECIALCHARS = "NS";

	/** EMAIL_TEMPLATE_VL_RESPONSE_FAILURE. */
	public static final int EMAIL_TEMPLATE_VL_RESPONSE_FAILURE = 99;

	/** FAILURE. */
	public static final int FAILURE = 0;

	/** FORMAT_TYPE_FIXED. */
	public static final String FORMAT_TYPE_FIXED = "FIXED";

	/** FORMAT_TYPE_LLLVAR. */
	public static final String FORMAT_TYPE_LLLVAR = "LLLVAR";

	/** FORMAT_TYPE_LLVAR. */
	public static final String FORMAT_TYPE_LLVAR = "LLVAR";

	/** IDENTIFIER_FULLFILLMENT_STAN_MAX. */
	public static final long IDENTIFIER_FULLFILLMENT_STAN_MAX = 999999;

	/** LEDGER_ENTRY_ID. */
	public static final String LEDGER_ENTRY_ID = "LEDGER_ENTRY_ID";

	/** LEDGER_TRANS_ID. */
	public static final String LEDGER_TRANS_ID = "LEDGER_TRANS_ID";

	/** LEDGER_TRANS_ID_ADD_VALUE. */
	public static final long LEDGER_TRANS_ID_ADD_VALUE = 100000000;

	/** MESSAGE_DESC_ID_ACTIVATION_RELOAD. */
	public static final long MESSAGE_DESC_ID_ACTIVATION_RELOAD = 1;

	/** MESSAGE_DESC_ID_BALANCE_CREDIT. */
	public static final long MESSAGE_DESC_ID_BALANCE_CREDIT = 10;

	/** MESSAGE_DESC_ID_BALANCE_DEBIT. */
	public static final long MESSAGE_DESC_ID_BALANCE_DEBIT = 12;

	/** MESSAGE_DESC_ID_BALANCE_ENQ. */
	public static final long MESSAGE_DESC_ID_BALANCE_ENQ = 5;

	/** MESSAGE_DESC_ID_HEARTBEAT. */
	public static final long MESSAGE_DESC_ID_HEARTBEAT = 7;

	/** MESSAGE_DESC_ID_REDEMPTION. */
	public static final long MESSAGE_DESC_ID_REDEMPTION = 3;

	/** MESSAGE_DESC_ID_VOID. */
	public static final long MESSAGE_DESC_ID_VOID = 14;

	/** MESSAGE_TYPE_ACTIVATION. */
	public static final int MESSAGE_TYPE_ACTIVATION = 1;

	/** MESSAGE_TYPE_BALANCE_ENQ. */
	public static final int MESSAGE_TYPE_BALANCE_ENQ = 4;

	/** MESSAGE_TYPE_HEARTBEAT. */
	public static final int MESSAGE_TYPE_HEARTBEAT = 5;

	/** MESSAGE_TYPE_REDEMPTION. */
	public static final int MESSAGE_TYPE_REDEMPTION = 3;

	/** MESSAGE_TYPE_RELOAD. */
	public static final int MESSAGE_TYPE_RELOAD = 2;

	/** MESSAGE_TYPE_VOID. */
	public static final int MESSAGE_TYPE_VOID = 6;

	// ######################## VL PROMO CODES ########################
	/** NEW_BUYER_ACTIVATE_V1_PROMO_CODE_ID. */
	public final static int NEW_BUYER_ACTIVATE_V1_PROMO_CODE_ID = 1;

	/** NEW_BUYER_ACTIVATE_V2_PROMO_CODE_ID. */
	public final static int NEW_BUYER_ACTIVATE_V2_PROMO_CODE_ID = 2;

	/** NEW_PROVIDER_ACTIVATE_V1_PROMO_CODE_ID. */
	public final static int NEW_PROVIDER_ACTIVATE_V1_PROMO_CODE_ID = 3;

	/** REDEMPTION_REQUEST. */
	public static final String REDEMPTION_REQUEST = "REDEMPTION_REQUEST";

	/** REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID. */
	public static final String REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID = "REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID";

	/** REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID_RESPONSE. */
	public static final String REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID_RESPONSE = "REDEMPTION_REQUEST_PARTIAL_APPROVAL_VOID_RESPONSE";

	/** REDEMPTION_RESPONSE. */
	public static final String REDEMPTION_RESPONSE = "REDEMPTION_RESPONSE";

	/** REDEMPTION_RESPONSE_PARTIAL. */
	public static final String REDEMPTION_RESPONSE_PARTIAL = "REDEMPTION_RESPONSE_PARTIAL";

	/** RESPONSE_ACTION_CODE_AUTHORIZER_UNAVAILABLE. */
	public static final String RESPONSE_ACTION_CODE_AUTHORIZER_UNAVAILABLE = "912";

	/** RESPONSE_ACTION_CODE_CANNOT_PARSE_MESSAGE. */
	public static final String RESPONSE_ACTION_CODE_CANNOT_PARSE_MESSAGE = "680";

	/** RESPONSE_ACTION_CODE_CARD_NOT_EFFECTIVE. */
	public static final String RESPONSE_ACTION_CODE_CARD_NOT_EFFECTIVE = "125";

	/** RESPONSE_ACTION_CODE_DECLINE. */
	public static final String RESPONSE_ACTION_CODE_DECLINE = "100";

	/** RESPONSE_ACTION_CODE_EXTERNAL_FORMAT_ERROR. */
	public static final String RESPONSE_ACTION_CODE_EXTERNAL_FORMAT_ERROR = "904";

	/** RESPONSE_ACTION_CODE_INTERNAL_FORMAT_ERROR. */
	public static final String RESPONSE_ACTION_CODE_INTERNAL_FORMAT_ERROR = "999";

	/** RESPONSE_ACTION_CODE_PARTIAL_APPROVAL. */
	public static final String RESPONSE_ACTION_CODE_PARTIAL_APPROVAL = "002";

	/** RESPONSE_ACTION_CODE_SUSPECT. */
	public static final String RESPONSE_ACTION_CODE_SUSPECT = "210";

	/** RESPONSE_ACTION_CODE_UNMAPPED. */
	public static final long RESPONSE_ACTION_CODE_UNMAPPED = 22;

	/** RESPONSE_ACTION_CODE_VERIFYCARD. */
	public static final String RESPONSE_ACTION_CODE_VERIFYCARD = "102";

	/** RULE_ID_ACH_ACTIVATE_RELOAD_BUYER_V1. */
	public final static int RULE_ID_ACH_ACTIVATE_RELOAD_BUYER_V1 = 4900;

	/** RULE_ID_ADMIN_AMEX_REFUND_REDEEM_BUYER_V1. */
	public final static int RULE_ID_ADMIN_AMEX_REFUND_REDEEM_BUYER_V1 = 4800;

	/** RULE_ID_ADMIN_VMC_REFUND_REDEEM_BUYER_V1. */
	public final static int RULE_ID_ADMIN_VMC_REFUND_REDEEM_BUYER_V1 = 4700;

	/** RULE_ID_BUYER_DEPOSIT_RELOAD_V1. */
	public final static int RULE_ID_BUYER_DEPOSIT_RELOAD_V1 = 3000;

	/** RULE_ID_BUYER_WITHDRAW_FUNDS_REDEEM_BUYER_V1. */
	public final static int RULE_ID_BUYER_WITHDRAW_FUNDS_REDEEM_BUYER_V1 = 3900;

	/** RULE_ID_CANCEL_ACH_SO_WO_PENALTY_RELOAD_BUYER_V1. */
	public final static int RULE_ID_CANCEL_ACH_SO_WO_PENALTY_RELOAD_BUYER_V1 = 3520;

	/** RULE_ID_CANCEL_SO_PENALTY_ACH_REDEEM_BUYER_V1. */
	public final static int RULE_ID_CANCEL_SO_PENALTY_ACH_REDEEM_BUYER_V1 = 3630;

	/** RULE_ID_CANCEL_SO_PENALTY_REDEEM_BUYER_V2. */
	public final static int RULE_ID_CANCEL_SO_PENALTY_REDEEM_BUYER_V2 = 3600;

	/** RULE_ID_CANCEL_SO_PENALTY_RELOAD_BUYER_V1. */
	public final static int RULE_ID_CANCEL_SO_PENALTY_RELOAD_BUYER_V1 = 3620;

	/** RULE_ID_CANCEL_SO_PENALTY_RELOAD_PROVIDER_V1. */
	public final static int RULE_ID_CANCEL_SO_PENALTY_RELOAD_PROVIDER_V1 = 3610;

	/** RULE_ID_CANCEL_SO_WO_PENALTY_REDEEM_BUYER_V2. */
	public final static int RULE_ID_CANCEL_SO_WO_PENALTY_REDEEM_BUYER_V2 = 3500;

	/** RULE_ID_CANCEL_SO_WO_PENALTY_RELOAD_BUYER_V1. */
	public final static int RULE_ID_CANCEL_SO_WO_PENALTY_RELOAD_BUYER_V1 = 3510;

	/** RULE_ID_DECREASE_ESCROW_ACH_REDEEM_BUYER_V1. */
	public final static int RULE_ID_DECREASE_ESCROW_ACH_REDEEM_BUYER_V1 = 3320;

	/** RULE_ID_DECREASE_ESCROW_REDEEM_BUYER_V2. */
	public final static int RULE_ID_DECREASE_ESCROW_REDEEM_BUYER_V2 = 3300;

	/** RULE_ID_DECREASE_ESCROW_RELOAD_BUYER_V1. */
	public final static int RULE_ID_DECREASE_ESCROW_RELOAD_BUYER_V1 = 3310;

	/** RULE_ID_INCREASE_ESCROW_ACH_RELOAD_BUYER_V1. */
	public final static int RULE_ID_INCREASE_ESCROW_ACH_RELOAD_BUYER_V1 = 3220;

	/** RULE_ID_INCREASE_ESCROW_REDEEM_BUYER_V1. */
	public final static int RULE_ID_INCREASE_ESCROW_REDEEM_BUYER_V1 = 3200;

	/** RULE_ID_INCREASE_ESCROW_RELOAD_BUYER_V2. */
	public final static int RULE_ID_INCREASE_ESCROW_RELOAD_BUYER_V2 = 3210;

	/** RULE_ID_NEW_BUYER_ACTIVATE_V1. */
	public final static int RULE_ID_NEW_BUYER_ACTIVATE_V1 = 2200;

	/** RULE_ID_NEW_BUYER_ACTIVATE_V2. */
	public final static int RULE_ID_NEW_BUYER_ACTIVATE_V2 = 2210;

	// ######################## FULLFILLMENT RULE IDs ########################
	/** RULE_ID_NEW_PROVIDER_ACTIVATE_V1. */
	public final static int RULE_ID_NEW_PROVIDER_ACTIVATE_V1 = 2100;

	/** RULE_ID_POST_SO_ACH_RELOAD_BUYER_V1. */
	public final static int RULE_ID_POST_SO_ACH_RELOAD_BUYER_V1 = 3130;

	/** RULE_ID_POST_SO_REDEEM_BUYER_V1. */
	public final static int RULE_ID_POST_SO_REDEEM_BUYER_V1 = 3100;

	/** RULE_ID_POST_SO_RELOAD_BUYER_V2. */
	public final static int RULE_ID_POST_SO_RELOAD_BUYER_V2 = 3120;

	/** RULE_ID_POST_SO_RELOAD_SL1. */
	public final static int RULE_ID_POST_SO_RELOAD_SL1 = 3110;

	/** RULE_ID_PROVIDER_WITHDRAW_FUNDS_REDEEM_PROVIDER_V1. */
	public final static int RULE_ID_PROVIDER_WITHDRAW_FUNDS_REDEEM_PROVIDER_V1 = 3800;

	/** RULE_ID_PROVIDER_WITHDRAW_REVERSAL_RELOAD_PROVIDER_V1. */
	public final static int RULE_ID_PROVIDER_WITHDRAW_REVERSAL_RELOAD_PROVIDER_V1 = 4000;

	/** RULE_ID_RELEASE_SO_PAYMENT_ACH_REDEEM_BUYER_V1. */
	public final static int RULE_ID_RELEASE_SO_PAYMENT_ACH_REDEEM_BUYER_V1 = 3740;

	/** RULE_ID_RELEASE_SO_PAYMENT_REDEEM_BUYER_V2. */
	public final static int RULE_ID_RELEASE_SO_PAYMENT_REDEEM_BUYER_V2 = 3700;

	/** RULE_ID_RELEASE_SO_PAYMENT_RELOAD_BUYER_V1. */
	public final static int RULE_ID_RELEASE_SO_PAYMENT_RELOAD_BUYER_V1 = 3730;

	/** RULE_ID_RELEASE_SO_PAYMENT_RELOAD_PROVIDER_V1. */
	public final static int RULE_ID_RELEASE_SO_PAYMENT_RELOAD_PROVIDER_V1 = 3720;

	/** RULE_ID_RELEASE_SO_PAYMENT_RELOAD_SL1. */
	public final static int RULE_ID_RELEASE_SO_PAYMENT_RELOAD_SL1 = 3710;

	/** RULE_ID_SLA_DEPOSIT_RELOAD_SL3. */
	public final static int RULE_ID_SLA_DEPOSIT_RELOAD_SL3 = 4200;

	/** RULE_ID_SLA_WITHDRAW_REDEEM_SL3. */
	public final static int RULE_ID_SLA_WITHDRAW_REDEEM_SL3 = 4210;

	/** RULE_ID_TRANSFER_SLB_FROM_BUYER_REDEEM_BUYER_V1. */
	public final static int RULE_ID_TRANSFER_SLB_FROM_BUYER_REDEEM_BUYER_V1 = 4500;

	/** RULE_ID_TRANSFER_SLB_FROM_BUYER_RELOAD_SL3. */
	public final static int RULE_ID_TRANSFER_SLB_FROM_BUYER_RELOAD_SL3 = 4510;

	/** RULE_ID_TRANSFER_SLB_FROM_PROVIDER_REDEEM_PROVIDER_V1. */
	public final static int RULE_ID_TRANSFER_SLB_FROM_PROVIDER_REDEEM_PROVIDER_V1 = 4600;

	/** RULE_ID_TRANSFER_SLB_FROM_PROVIDER_RELOAD_SL3. */
	public final static int RULE_ID_TRANSFER_SLB_FROM_PROVIDER_RELOAD_SL3 = 4610;

	/** RULE_ID_TRANSFER_SLB_TO_BUYER_REDEEM_SL3. */
	public final static int RULE_ID_TRANSFER_SLB_TO_BUYER_REDEEM_SL3 = 4300;

	/** RULE_ID_TRANSFER_SLB_TO_BUYER_RELOAD_BUYER_V1. */
	public final static int RULE_ID_TRANSFER_SLB_TO_BUYER_RELOAD_BUYER_V1 = 4310;

	/** RULE_ID_TRANSFER_SLB_TO_PROVIDER_REDEEM_SL3. */
	public final static int RULE_ID_TRANSFER_SLB_TO_PROVIDER_REDEEM_SL3 = 4400;

	/** RULE_ID_TRANSFER_SLB_TO_PROVIDER_RELOAD_PROVIDER_V1. */
	public final static int RULE_ID_TRANSFER_SLB_TO_PROVIDER_RELOAD_PROVIDER_V1 = 4410;

	/** RULE_ID_VOID_SO_ACH_REDEEM_BUYER_V1. */
	public final static int RULE_ID_VOID_SO_ACH_REDEEM_BUYER_V1 = 3420;

	/** RULE_ID_VOID_SO_REDEEM_BUYER_V2. */
	public final static int RULE_ID_VOID_SO_REDEEM_BUYER_V2 = 3400;

	/** RULE_ID_VOID_SO_RELOAD_BUYER_V1. */
	public final static int RULE_ID_VOID_SO_RELOAD_BUYER_V1 = 3410;

	/** RULE_ID_WITHDRAW_SL_REVENUE_REDEEM_SL1. */
	public final static int RULE_ID_WITHDRAW_SL_REVENUE_REDEEM_SL1 = 4100;

	/** RULE_ID_WITHDRAW_SL_REVENUE_REDEEM_SL2. */
	public final static int RULE_ID_WITHDRAW_SL_REVENUE_REDEEM_SL2 = 4110;

	/** SHARP_DUMMY_PAN_NUMBER. */
	public static final String SHARP_DUMMY_PAN_NUMBER = "9797979999999991";

	/** SHARP_HEARTBEAT_REQUEST. */
	public static final String SHARP_HEARTBEAT_REQUEST = "SHARP_HEARTBEAT_REQUEST";

	/** SHARP_HEARTBEAT_RESPONSE. */
	public static final String SHARP_HEARTBEAT_RESPONSE = "SHARP_HEARTBEAT_RESPONSE";

	/** SHARP_P63_ACCOUNT_NUMBER. */
	public static final String SHARP_P63_ACCOUNT_NUMBER = "AN";

	/** SHARP_P63_FULFILLMENT_GROUP. */
	public static final String SHARP_P63_FULFILLMENT_GROUP = "FG";

	/** SHARP_P63_LEDGER_ACCOUNT. */
	public static final String SHARP_P63_LEDGER_ACCOUNT = "LA";

	/** SHARP_P63_PROMO_CODE. */
	public static final String SHARP_P63_PROMO_CODE = "PC";

	/** SHARP_QUEUE. */
	public static final String SHARP_QUEUE = "sharpQueue";

	/** SHARP_REQUEST_MTI. */
	public static final String SHARP_REQUEST_MTI = "1200";

	/** SHARP_RESPONSE_MTI. */
	public static final String SHARP_RESPONSE_MTI = "1210";

	/** SHARP_SYSTEM. */
	public static final String SHARP_SYSTEM = "sharp";

	/** STAN_ID. */
	public static final String STAN_ID = "STAN_ID";

	/** STR_ADMIN. */
	public static final String STR_ADMIN = "admin";

	/** SUCCESS. */
	public static final int SUCCESS = 1;

	/** VALUELINK_QUEUE. */
	public static final String VALUELINK_QUEUE = "valueLinkQueue";

	/** VL_ACCOUNT_BUYER_V1. */
	public static final String VL_ACCOUNT_BUYER_V1 = "V1";

	/** VL_ACCOUNT_BUYER_V2. */
	public static final String VL_ACCOUNT_BUYER_V2 = "V2";

	/** VL_ACCOUNT_CC_FEE. */
	public final static String VL_ACCOUNT_CC_FEE = "SL5";

	// ######################## SL - VL Accounts ########################
	/** VL_ACCOUNT_POSTING_FEE. */
	public final static String VL_ACCOUNT_POSTING_FEE = "SL1";

	/** VL_ACCOUNT_PREFUNDING_ACCOUNT. */
	public final static String VL_ACCOUNT_PREFUNDING_ACCOUNT = "SL3";

	/** VL_ACCOUNT_PROVIDER_V1. */
	public static final String VL_ACCOUNT_PROVIDER_V1 = "V1";

	/** VL_ACCOUNT_SERVICE_FEE. */
	public final static String VL_ACCOUNT_SERVICE_FEE = "SL2";

	/** VL_ACCOUNT_SL_EXPENSES. */
	public final static String VL_ACCOUNT_SL_EXPENSES = "SL4";

	/** VL_SYSTEM. */
	public static final String VL_SYSTEM = "valuelink";

}
