package com.servicelive.wallet.common;

// TODO: Auto-generated Javadoc
/**
 * Class WalletConstants.
 */
public class WalletConstants {

	/** BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_AMEX. */
	public final static long BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_AMEX = 270;

	/** BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_SEARS. */
	public final static long BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_SEARS = 300;

	// ########################Entity Type Id########################

	/** BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_V_MX. */
	public final static long BUSINESS_TRANSACTION_BUYER_DEPOSITS_FROM_V_MX = 260;

	/** BUSINESS_TRANSACTION_BUYER_INSTANT_ACH_DEPOSIT. */
	public final static long BUSINESS_TRANSACTION_BUYER_INSTANT_ACH_DEPOSIT = 310;

	/** BUSINESS_TRANSACTION_BUYER_INSTANT_ACH_REFUND. */
	public final static long BUSINESS_TRANSACTION_BUYER_INSTANT_ACH_REFUND = 320;

	/** BUSINESS_TRANSACTION_BUYER_REFUND. */
	public final static long BUSINESS_TRANSACTION_BUYER_REFUND = 250;

	/** BUSINESS_TRANSACTION_CANCEL_SO. */
	public final static long BUSINESS_TRANSACTION_CANCEL_SO = 110;

	/** BUSINESS_TRANSACTION_CANCEL_SO_WO_PENALTY. */
	public final static long BUSINESS_TRANSACTION_CANCEL_SO_WO_PENALTY = 111;

	/** BUSINESS_TRANSACTION_CLOSE_SO. */
	public final static long BUSINESS_TRANSACTION_CLOSE_SO = 130;

	/** BUSINESS_TRANSACTION_DECREASE_SO_ESCROW. */
	public final static long BUSINESS_TRANSACTION_DECREASE_SO_ESCROW = 160;

	/** BUSINESS_TRANSACTION_DEPOSIT_FUNDS_BUYER_REVERSAL. */
	public final static long BUSINESS_TRANSACTION_DEPOSIT_FUNDS_BUYER_REVERSAL = 50;

	// ######################## TRANSACTION_ID ########################
	/** BUSINESS_TRANSACTION_DEPOSITS_FUNDS_BUYER. */
	public final static long BUSINESS_TRANSACTION_DEPOSITS_FUNDS_BUYER = 10;

	/** BUSINESS_TRANSACTION_INCREASE_SO_ESCROW. */
	public final static long BUSINESS_TRANSACTION_INCREASE_SO_ESCROW = 150;

	// ########################Transaction Type Id########################

	/** BUSINESS_TRANSACTION_MARKETPLACE_WITHDRAW_FUNDS. */
	public final static long BUSINESS_TRANSACTION_MARKETPLACE_WITHDRAW_FUNDS = 140;

	/** BUSINESS_TRANSACTION_NEW_BUYER. */
	public final static long BUSINESS_TRANSACTION_NEW_BUYER = 180;

	/** BUSINESS_TRANSACTION_NEW_PROVIDER. */
	public final static long BUSINESS_TRANSACTION_NEW_PROVIDER = 170;

	/** BUSINESS_TRANSACTION_POST_SO. */
	public final static long BUSINESS_TRANSACTION_POST_SO = 100;

	/** BUSINESS_TRANSACTION_RELEASE_SO_PAYMENT. */
	public final static long BUSINESS_TRANSACTION_RELEASE_SO_PAYMENT = 120;

	/** BUSINESS_TRANSACTION_SLA_CREDITS_SLB_TO_BUYER. */
	public final static long BUSINESS_TRANSACTION_SLA_CREDITS_SLB_TO_BUYER = 210;

	/** BUSINESS_TRANSACTION_SLA_CREDITS_SLB_TO_PROVIDER. */
	public final static long BUSINESS_TRANSACTION_SLA_CREDITS_SLB_TO_PROVIDER = 220;

	/** BUSINESS_TRANSACTION_SLA_DEBITS_SLB_FROM_BUYER. */
	public final static long BUSINESS_TRANSACTION_SLA_DEBITS_SLB_FROM_BUYER = 230;

	/** BUSINESS_TRANSACTION_SLA_DEBITS_SLB_FROM_PROVIDER. */
	public final static long BUSINESS_TRANSACTION_SLA_DEBITS_SLB_FROM_PROVIDER = 240;

	/** BUSINESS_TRANSACTION_SLA_DEPOSITS_TO_OPERATIONS. */
	public final static long BUSINESS_TRANSACTION_SLA_DEPOSITS_TO_OPERATIONS = 190;

	/** BUSINESS_TRANSACTION_SLA_WITHDRAWS_FROM_OPERATIONS. */
	public final static long BUSINESS_TRANSACTION_SLA_WITHDRAWS_FROM_OPERATIONS = 200;

	/** BUSINESS_TRANSACTION_VOID_SO. */
	public final static long BUSINESS_TRANSACTION_VOID_SO = 115;

	/** BUSINESS_TRANSACTION_WITHDRAW_FUNDS_BUYER. */
	public final static long BUSINESS_TRANSACTION_WITHDRAW_FUNDS_BUYER = 30;

	/** BUSINESS_TRANSACTION_WITHDRAW_FUNDS_PROVIDER. */
	public final static long BUSINESS_TRANSACTION_WITHDRAW_FUNDS_PROVIDER = 20;

	/** BUSINESS_TRANSACTION_WITHDRAW_FUNDS_PROVIDER_REVERSAL. */
	public final static long BUSINESS_TRANSACTION_WITHDRAW_FUNDS_PROVIDER_REVERSAL = 40;

	/** BUSINESS_TRANSACTION_WITHDRAW_FUNDS_TO_BUYERS_AMEX. */
	public final static long BUSINESS_TRANSACTION_WITHDRAW_FUNDS_TO_BUYERS_AMEX = 290;

	/** BUSINESS_TRANSACTION_WITHDRAW_FUNDS_TO_BUYERS_V_MC. */
	public final static long BUSINESS_TRANSACTION_WITHDRAW_FUNDS_TO_BUYERS_V_MC = 280;

	/** ENTITY_ID_DEPOSIT_WITHDRAWL. */
	public final static long ENTITY_ID_DEPOSIT_WITHDRAWL = 7;

	/** ENTITY_ID_ESCROW. */
	public final static long ENTITY_ID_ESCROW = 2;

	/** ENTITY_ID_MANAGED_SERVICES. */
	public final static long ENTITY_ID_MANAGED_SERVICES = 3;

	// ########################Financial Type Id########################
	/** ENTITY_ID_SERVICELIVE. */
	public final static long ENTITY_ID_SERVICELIVE = 1;

	/** ENTITY_ID_SERVICELIVE_OPERATION. */
	public final static long ENTITY_ID_SERVICELIVE_OPERATION = 9;

	/** ENTITY_ID_VIRTUAL_CASH. */
	public final static long ENTITY_ID_VIRTUAL_CASH = 8;

	/** ENTRY_TYPE_CREDIT. */
	public final static int ENTRY_TYPE_CREDIT = 2;

	// ########################NEW ENTRY TYPE ID ########################
	/** ENTRY_TYPE_DEBIT. */
	public final static int ENTRY_TYPE_DEBIT = 1;

	/** FUNDING_TYPE_DIRECT_FUNDED. */
	public final static long FUNDING_TYPE_DIRECT_FUNDED = 20;

	// ########################Funding Type complete########################
	/** FUNDING_TYPE_NON_FUNDED. */
	public final static long FUNDING_TYPE_NON_FUNDED = 10;

	/** FUNDING_TYPE_PRE_FUNDED. */
	public final static long FUNDING_TYPE_PRE_FUNDED = 30;

	/** LEDGER_ENTITY_TYPE_BUYER. */
	public final static long LEDGER_ENTITY_TYPE_BUYER = 10;

	/** LEDGER_ENTITY_TYPE_DEPOSITS_WITHDRAWLS. */
	public final static long LEDGER_ENTITY_TYPE_DEPOSITS_WITHDRAWLS = 70;

	/** LEDGER_ENTITY_TYPE_FIRSTDATA. */
	public final static long LEDGER_ENTITY_TYPE_FIRSTDATA = 60;

	/** LEDGER_ENTITY_TYPE_MANAGE_SERVICES. */
	public final static long LEDGER_ENTITY_TYPE_MANAGE_SERVICES = 50;

	/** LEDGER_ENTITY_TYPE_PROVIDER. */
	public final static long LEDGER_ENTITY_TYPE_PROVIDER = 20;

	/** LEDGER_ENTITY_TYPE_SERVICELIVE_ESCROW. */
	public final static long LEDGER_ENTITY_TYPE_SERVICELIVE_ESCROW = 30;

	/** LEDGER_ENTITY_TYPE_SERVICELIVE_MAIN. */
	public final static long LEDGER_ENTITY_TYPE_SERVICELIVE_MAIN = 40;

	/** LEDGER_ENTITY_TYPE_SERVICELIVE_OPERATION. */
	public final static long LEDGER_ENTITY_TYPE_SERVICELIVE_OPERATION = 90;

	/** LEDGER_ENTITY_TYPE_VIRTUAL_CASH. */
	public final static long LEDGER_ENTITY_TYPE_VIRTUAL_CASH = 80;

	/** PTD_RECONCILATION_STATUS_MARKED. */
	public static final int PTD_RECONCILATION_STATUS_MARKED = 10;

	/** PTD_RECONCILATION_STATUS_SUCCESS. */
	public static final int PTD_RECONCILATION_STATUS_SUCCESS = 10;

	/** SHC_FUNDING_TYPE. */
	public final static long SHC_FUNDING_TYPE = 40;

	/** SL_STORE_NO. */
	public static final String SL_STORE_NO = "sl_store_no";

	/** SL_STORE_NO_WO_ZERO. */
	public static final String SL_STORE_NO_WO_ZERO = "sl_store_no_wo_zero";

	/** TRANSACTION_TYPE_ID_ACTUAL_RETAIL. */
	public final static long TRANSACTION_TYPE_ID_ACTUAL_RETAIL = 900;

	/** TRANSACTION_TYPE_ID_CANCELLED_ORDER. */
	public final static long TRANSACTION_TYPE_ID_CANCELLED_ORDER = 600;

	/** TRANSACTION_TYPE_ID_CANCELLED_PENALTY. */
	public final static long TRANSACTION_TYPE_ID_CANCELLED_PENALTY = 700;

	/** TRANSACTION_TYPE_ID_CREDIT_DEPOSIT. */
	public final static long TRANSACTION_TYPE_ID_CREDIT_DEPOSIT = 1200;

	/** TRANSACTION_TYPE_ID_CREDIT_WITHDRAWAL. */
	public final static long TRANSACTION_TYPE_ID_CREDIT_WITHDRAWAL = 1400;

	/** TRANSACTION_TYPE_ID_DEPOSIT_CASH. */
	public final static long TRANSACTION_TYPE_ID_DEPOSIT_CASH = 100;

	/** TRANSACTION_TYPE_ID_INSTANT_ACH_DEPOSIT. */
	public final static long TRANSACTION_TYPE_ID_INSTANT_ACH_DEPOSIT = 1900;

	/** TRANSACTION_TYPE_ID_INSTANT_ACH_REFUND. */
	public final static long TRANSACTION_TYPE_ID_INSTANT_ACH_REFUND = 1901;

	/** TRANSACTION_TYPE_ID_ORDER_ESCROW. */
	public final static long TRANSACTION_TYPE_ID_ORDER_ESCROW = 400;

	/** TRANSACTION_TYPE_ID_ORDER_PAYMENT. */
	public final static long TRANSACTION_TYPE_ID_ORDER_PAYMENT = 500;

	/** TRANSACTION_TYPE_ID_POSTING_FEE. */
	public final static long TRANSACTION_TYPE_ID_POSTING_FEE = 200; // aka

	/** TRANSACTION_TYPE_ID_SERVICE_FEE. */
	public final static long TRANSACTION_TYPE_ID_SERVICE_FEE = 300;

	/** TRANSACTION_TYPE_ID_TRANSFER_FUNDS. */
	public final static long TRANSACTION_TYPE_ID_TRANSFER_FUNDS = 1300;

	/** TRANSACTION_TYPE_ID_VOIDED_ORDER. */
	public final static long TRANSACTION_TYPE_ID_VOIDED_ORDER = 750;

	/** TRANSACTION_TYPE_ID_WITHDRAW_CASH. */
	public final static long TRANSACTION_TYPE_ID_WITHDRAW_CASH = 800;

	/** BUYER_ROLE. */
	public static final String BUYER_ROLE = "BUYER";

	/** PROVIDER_ROLE. */
	public static final String PROVIDER_ROLE = "PROVIDER";

	/** SERVICELIVE_ROLE. */
	public static final String SERVICELIVE_ROLE = "SERVICELIVE";
}
