package com.servicelive.spn.common.detached.counterbucket;

public enum BucketType {
	SPN,
	PROVIDER_FIRM,
	SERVICE_PROVIDER,
	INVITED_COMPOSITE,
	INTERESTED_COMPOSITE,
	NOT_INTERESTED_COMPOSITE,
	APPLIED_COMPOSITE,
	DECLINED_COMPOSITE,
	APPLICATION_INCOMPLETE_COMPOSITE,
	INACTIVE_COMPOSITE,
	ACTIVE_COMPOSITE,
	REMOVED_COMPOSITE,
}
