--Campaign Activation
INSERT INTO QRTZ_JOB_DETAILS
(JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_VOLATILE, IS_STATEFUL, REQUESTS_RECOVERY, JOB_DATA) 
VALUES('SPN_CAM_ACT', 'GRP_SPN', 'Changes the state of the Campaign status from APPROVED to ACTIVE', 'com.servicelive.spn.scheduler.quartz.CampaignActivateScheduler', 'Y', 'N', 'N', 'N', NULL);


INSERT INTO QRTZ_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, IS_VOLATILE, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, PRIORITY, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA) 
 VALUES('TRG_SPN_CAM_ACT', 'TRG_GRP_SPN', 'SPN_CAM_ACT', 'GRP_SPN', '0', 'SPN Campaign Approved to Active', 0, 0, 0, 'WAITING', 'CRON', 0, 0, null, 2, NULL);

INSERT INTO QRTZ_CRON_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, CRON_EXPRESSION, TIME_ZONE_ID) 
VALUES('TRG_SPN_CAM_ACT', 'TRG_GRP_SPN', '0 0/5 * * * ?', 'America/Chicago');

--Campaign Invitation
INSERT INTO QRTZ_JOB_DETAILS
(JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_VOLATILE, IS_STATEFUL, REQUESTS_RECOVERY, JOB_DATA) 
VALUES('SPN_CAM_INV', 'GRP_SPN', 'Emails SPN Campaigns when Campaign is Active',  'com.servicelive.spn.scheduler.quartz.CampaignInvitationScheduler', 'Y', 'N', 'N', 'N', NULL);


INSERT INTO QRTZ_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, IS_VOLATILE, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, PRIORITY, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA) 
 VALUES('TRG_SPN_CAM_INV', 'TRG_GRP_SPN', 'SPN_CAM_INV', 'GRP_SPN', '0', 'Emails SPN Campaigns when Campaign is Active', 0, 0, 0, 'WAITING', 'CRON', 0, 0, null, 2, NULL);

INSERT INTO QRTZ_CRON_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, CRON_EXPRESSION, TIME_ZONE_ID) 
VALUES('TRG_SPN_CAM_INV', 'TRG_GRP_SPN', '0 0/5 * * * ?', 'America/Chicago');
