delete from QRTZ_CRON_TRIGGERS where TRIGGER_NAME='TRG_SPN_MEM_MAIN';

delete from QRTZ_TRIGGERS where JOB_NAME = 'SPN_MEM_MAIN';

delete from QRTZ_JOB_DETAILS where JOB_NAME = 'SPN_MEM_MAIN';

delete from QRTZ_CRON_TRIGGERS where TRIGGER_NAME='TRG_SPN_EDIT_NET';

delete from QRTZ_TRIGGERS where JOB_NAME = 'SPN_EDIT_NET';

delete from QRTZ_JOB_DETAILS where JOB_NAME = 'SPN_EDIT_NET';

--Member Maintenance
INSERT INTO QRTZ_JOB_DETAILS
(JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_VOLATILE, IS_STATEFUL, REQUESTS_RECOVERY, JOB_DATA) 
VALUES('SPN_MEM_MAIN', 'GRP_SPN', 'Changes the states of the Provider Firm and Service Providers from either in compliance or out of compliance',  'com.servicelive.spn.scheduler.quartz.MemberMaintenanceScheduler', 'Y', 'N', 'N', 'N', NULL);


INSERT INTO QRTZ_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, IS_VOLATILE, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, PRIORITY, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA) 
 VALUES('TRG_SPN_MEM_MAIN', 'TRG_GRP_SPN', 'SPN_MEM_MAIN', 'GRP_SPN', '0', 'Changes the states of the Provider Firm and Service Providers from either in compliance or out of compliance', 0, 0, 0, 'WAITING', 'CRON', 0, 0, null, 2, NULL);

INSERT INTO QRTZ_CRON_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, CRON_EXPRESSION, TIME_ZONE_ID) 
VALUES('TRG_SPN_MEM_MAIN', 'TRG_GRP_SPN', '0 10 0 * * ?', 'America/Chicago');

--Edit Network
INSERT INTO QRTZ_JOB_DETAILS
(JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_VOLATILE, IS_STATEFUL, REQUESTS_RECOVERY, JOB_DATA) 
VALUES('SPN_EDIT_NET', 'GRP_SPN', 'Cleans out the expired SPN alias information',  'com.servicelive.spn.scheduler.quartz.EditNetworkScheduler', 'Y', 'N', 'N', 'N', NULL);


INSERT INTO QRTZ_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, IS_VOLATILE, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, PRIORITY, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA) 
 VALUES('TRG_SPN_EDIT_NET', 'TRG_GRP_SPN', 'SPN_EDIT_NET', 'GRP_SPN', '0',  'Cleans out the expired SPN alias information', 0, 0, 0, 'WAITING', 'CRON', 0, 0, null, 2, NULL);

INSERT INTO QRTZ_CRON_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, CRON_EXPRESSION, TIME_ZONE_ID) 
VALUES('TRG_SPN_EDIT_NET', 'TRG_GRP_SPN', '0 50 0 * * ?', 'America/Chicago');


--network maintenance 

delete from QRTZ_CRON_TRIGGERS where TRIGGER_NAME='TRG_SPN_NET_MAIN';

delete from QRTZ_TRIGGERS where JOB_NAME = 'SPN_NET_MAIN';

delete from QRTZ_JOB_DETAILS where JOB_NAME = 'SPN_NET_MAIN';



INSERT INTO QRTZ_JOB_DETAILS
(JOB_NAME, JOB_GROUP, DESCRIPTION, JOB_CLASS_NAME, IS_DURABLE, IS_VOLATILE, IS_STATEFUL, REQUESTS_RECOVERY, JOB_DATA) 
VALUES('SPN_NET_MAIN', 'GRP_SPN', 'Changes the states of the Network COMPLETE or INCOMPLETE',  'com.servicelive.spn.scheduler.quartz.NetworkMaintenanceScheduler', 'Y', 'N', 'N', 'N', NULL);


INSERT INTO QRTZ_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, IS_VOLATILE, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, PRIORITY, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA) 
 VALUES('TRG_SPN_NET_MAIN', 'TRG_GRP_SPN', 'SPN_NET_MAIN', 'GRP_SPN', '0', 'Changes the states of the Network COMPLETE or INCOMPLETE', 0, 0, 0, 'WAITING', 'CRON', 0, 0, null, 2, NULL);

INSERT INTO QRTZ_CRON_TRIGGERS
(TRIGGER_NAME, TRIGGER_GROUP, CRON_EXPRESSION, TIME_ZONE_ID) 
VALUES('TRG_SPN_NET_MAIN', 'TRG_GRP_SPN', '0 10 2 * * ?', 'America/Chicago');