<jsp:include page="/jsp/public/common/commonIncludes.jsp" />
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="showTags" scope="request" value="1" />

<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title>ServiceLive [Terms of Use]</title><link rel="shortcut icon" href="${staticContextPath}/images/favicon.ico" />

		<style type="text/css">
@import "${staticContextPath}/javascript/dojo/dijit/themes/tundra/tundra.css";

@import "${staticContextPath}/javascript/dojo/dijit/themes/tundra/tundra_rtl.css";
</style>
		<link rel="stylesheet" type="text/css"
			href="${staticContextPath}/css/dijitTitlePane-serviceLive.css">
		<link rel="stylesheet" type="text/css"
			href="${staticContextPath}/css/dijitTabPane-serviceLive.css">
		<link rel="stylesheet" type="text/css" href="${staticContextPath}/css/main.css" />
		<link rel="stylesheet" type="text/css" href="${staticContextPath}/css/iehacks.css" />
		<link rel="stylesheet" type="text/css"
			href="${staticContextPath}/css/top-section.css" />
		<link rel="stylesheet" type="text/css" href="${staticContextPath}/css/tooltips.css" />
		<link rel="stylesheet" type="text/css" href="${staticContextPath}/css/buttons.css" />
		<script language="JavaScript" src="${staticContextPath}/javascript/tooltip.js"
			type="text/javascript"></script>
		<script language="JavaScript" type="text/javascript"
			src="${staticContextPath}/javascript/formfields.js"></script>
		<script type="text/javascript" src="${staticContextPath}/javascript/jquery/jquery.min.js"></script>
		
		<script language="JavaScript" type="text/javascript"
			src="${staticContextPath}/javascript/nav.js"></script>
			<style type="text/css">
			 .content li {
				padding: 4px 0;
			}
			</style>
			
			<jsp:include page="/jsp/public/common/omitInclude.jsp" flush="true">
			       <jsp:param name="PageName" value="TermsOfUse"/>
			</jsp:include>
	</head>
	<body class="tundra">
	<!--  <body class="tundra" onload="displayBanner()">-->
		<div id="page_margins">
			<div id="page">
				<!-- START HEADER -->
				<div id="header">
					<tiles:insertDefinition name="newco.base.topnav"/> 					
					<tiles:insertDefinition name="newco.base.blue_nav"/>
					<tiles:insertDefinition name="newco.base.dark_gray_nav"/>
					<div id="pageHeader">
						<img src="${staticContextPath}/images/common/hdr_termsOfUse.gif" width="119"
							height="14" alt="Terms of Use" title="Terms of Use" />
					</div>
				</div>
				<!-- END HEADER -->
				<div>
					<div class="content" style="color: #000; padding: 0 20px;">
							<p>By accessing or using any features of the site located at  www.ServiceLive.com (the "ServiceLive Site") and operated and managed by Transform ServiceLive LLC. ("ServiceLive" "us" or "we"), you agree to be bound by these terms of service (collectively, "Terms of Service"). All visitors to and users of any aspects of the ServiceLive Site (collectively, "Users") are bound by these Terms of Service.  We reserve the right to modify the Terms of Service at any time without prior notice to you.  Therefore, we recommend that you read these terms of service carefully each time you use this Web site.</p>
							<p>Please note that the guidelines, policies and other terms and conditions of service and use of other websites affiliated with either ServiceLive may vary from these Terms of Service.</p>
							<p>The ServiceLive Site is a venue connecting buyers ("Buyers") with Provider Firms and/or Service Pros (each a "Provider").  By using the ServiceLive Site you acknowledge that ServiceLive is not a participant in the transaction between the Buyers and the Providers and ServiceLive is not responsible for the content of Buyers' offers or for the performance of Services by Providers.  As a User of the ServiceLive Site, you may also post content and share it with other users, read content generated by other visitors to the ServiceLive Site and other affiliated sites, and view third party postings and reviews regarding products and services. If you wish to post content to, or participate in the ServiceLive Site other than simply by reading information and content and reviews posted by others, you must register using the registration form available at www.ServiceLive.com.  Users who wish to register as a Buyer must agreed to be bound by the <a href="termsAndConditions_displayBuyerAgreement.action">ServiceLive Buyer Agreement</a> (the "Buyer Agreement").    Users who wish to register as a Provider must agreed to be bound by the <a href="termsAndConditions_displayProviderAgreement.action">ServiceLive Service Provider Agreement</a> (the "Provider Agreement").</p>
							<p>These Terms of Service set out the legally binding terms with respect to your use of the ServiceLive Site. Please read these Terms of Service carefully. Your access to and use of the ServiceLive Site constitutes your acceptance of all the provisions of these Terms of Service. If you are unwilling to be bound by these Terms of Service, you should not access or use the ServiceLive Site</p>
							
							<h2>Eligibility</h2>
							<p>The ServiceLive Site is not targeted towards, nor intended for use by, anyone under the age of 18. By using the ServiceLive Site, you represent and warrant that you are 18 years of age or older. If you are not at least 18 years of age, do not access, use or register on the ServiceLive Site. In the event we become aware you are under 18, we will terminate your registration.</p>
						
						
							<h2>Changes to the ServiceLive Site</h2>
							<p>You agree and understand that the ServiceLive Site, including any and all features available via the ServiceLive Site and any User Content (as defined below), may be modified by us, in our sole discretion, at any time without prior notice. Unless expressly stated otherwise, any new features, new services, enhancements or modifications to the ServiceLive Site implemented after your initial access to the ServiceLive Site shall be subject to these Terms of Service. We undertake no obligation to monitor or modify, any reviews, information, content, data, text, links to third party websites, User profile information, sounds, photographs, graphics, video, messages or other materials made available via the ServiceLive Site by any User (all such items provided by Users, collectively, "User Content"). Nonetheless, we reserve the right to monitor and modify User Content and we reserve the right to investigate and take appropriate action, including legal action, in our sole discretion, against anyone who violates these Terms of Service, including without limitation, by removing any User Content posted in violation of these Terms of Service, terminating the registration of such violators or blocking such violators' use of the ServiceLive Site.</p>
							
							
							<h2>Registration</h2>
							<p>In order to access some features of the ServiceLive Site, you may be required to register and to provide a  user name,  valid email address  and ServiceLive will issue a user id number ("User ID") and a temporary password.  You may change your password when you log into ServiceLive Site.  If you register, you agree to provide us with accurate and complete registration information, and to inform us immediately of any updates or other changes to such information. For example, you may not: (i) enter, select or use a false name or an email address owned or controlled by another person with the intent to impersonate that person, or (ii) use as a User ID a name subject to any rights of a person other than yourself without appropriate authorization. Failure to comply with the terms of this paragraph shall constitute a material breach of these Terms of Service, which may result in immediate termination of your account. In addition, we reserve the right to refuse registration of, or cancel a User ID in our discretion. </p>
							
							
							<h2>Security</h2>
							<p>You shall be responsible for maintaining the confidentiality of your password, and you are fully responsible for all activities that occur under your User ID and password, whether or not you authorize such activities. You agree to (a) immediately notify us of any unauthorized use of your User ID or password of which you become aware, and (b) ensure that you exit from your account at the end of each session. </p>
							
							
							<h3>Blocking of IP Addresses.</h3>
							<p>In order to protect the integrity of the Site, ServiceLive reserves the right at any time, in its sole discretion, to block Users from certain IP addresses from accessing the Site.</p>
							
							
							<h2>Use of the Site/Services</h2>
							<p>You may use the ServiceLive Site to solicit opinions, ideas and other input from, and share ideas and opinions with, other Users, and to search the ServiceLive Site for User Content and business or product information. You may also invite people you know to join the ServiceLive Site. You acknowledge and agree that we do not control the User Content posted to the ServiceLive Site, or any links to other websites, including the content of any messages, and that we do not guarantee the accuracy, integrity or quality of any User Content. You further understand and agree that (i) we do not necessarily endorse, support, sanction, encourage, verify, or agree with the comments, opinions, or statements or other User Content posted on or otherwise displayed on or transmitted via the ServiceLive Site, or (ii) we do not make any promises, guarantees or warranties with respect to any of the User Content or products, services, information, content or materials featured or mentioned on the ServiceLive Site. All User Content, including advice and opinions posted by Users, comprises the views and responsibility of those who post such User Content, and does not necessarily represent the our views. You understand that, by using the ServiceLive Site, you may be exposed to User Content that is offensive, indecent or objectionable. </p>
							<p>IN NO EVENT WILL WE BE LIABLE, DIRECTLY OR INDIRECTLY, TO ANYONE FOR ANY DAMAGE OR LOSS OF ANY NATURE WHATSOEVER ARISING FROM OR RELATING TO ANY USE, CONTINUED USE OR RELIANCE ON ANY USER CONTENT, ANY ERROR OR OMISSION IN ANY USER CONTENT, ANY CLAIM THAT ANY USER CONTENT IS DEFAMATORY, LIBELOUS OR VIOLATES ANY RIGHT OF ANY THIRD PARTY, OR THE DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY USER OR THIRD PARTY. YOU EXPRESSLY AGREE THAT YOU BEAR ANY AND ALL RISKS ASSOCIATED WITH YOUR ACCESS TO, CONTRIBUTION TO, USE OF AND/OR RELIANCE ON USER CONTENT.</p>
							
							
							<h2>Restrictions on Rights to Use</h2>
							<p>Without limiting the generality of any other provisions of these Terms of Service, you agree you shall not (and you agree not to allow any other individual or entity to): </p>
							<ul style="margin: 20px;">
								<li>download, modify, reproduce, adapt, translate, reverse engineer, create derivative works based upon, publicly display, sell, rent, license, or in any way commercially exploit any portion of the ServiceLive Site, except and to the extent expressly permitted under these Terms of Service; </li>
								<li>remove any copyright, trademark or other proprietary rights notice contained in or on the ServiceLive Site; </li>
								<li>use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, "data mine", or in any way reproduce or circumvent the navigational structure or presentation of the ServiceLive Site or its contents. </li>
								<li>collect any information about other Users (including usernames, PII information and/or email addresses) for any purpose other than to provide or receive services which may be offered on the Site.</li>
								<li>reformat or frame any portion of any Web pages that are part of the ServiceLive Site; </li>
								<li>create user accounts by automated means or under false or fraudulent pretenses; </li>
								<li>create or transmit to other Users unsolicited electronic communications, such as "spam," or otherwise interfere with other Users' enjoyment of the ServiceLive Site; </li>
								<li>submit to the ServiceLive Site any content that falsely states or implies that such content is sponsored or endorsed by us; </li>
								<li>transmit or upload to the ServiceLive Site any item containing or embodying any virus, worm, defect, Trojan horse, software bomb or other feature designed to damage or degrade in any manner the performance of the ServiceLive Site, any other Web site, or any computer or other device or system, or the enjoyment of the ServiceLive Site by any User; </li>
								<li>use the ServiceLive Site to violate the security of or gain unauthorized access to any computer or computer network or other device or system (including unauthorized attempts to discover passwords or security encryption codes); </li>
								<li>submit to the ServiceLive Site any content that is unlawful or facilitates, constitutes, promotes or encourages illegal activity; or otherwise use the ServiceLive Site to transfer or store illegal material, including any material deemed threatening or obscene; </li>
								<li>copy or store any User Content offered on the ServiceLive Site other than for your personal, non-commercial use; </li>
								<li>take any action that imposes, or may impose, in our sole discretion, an unreasonable or disproportionately large load on the ServiceLive Site or the IT infrastructure used to operate and make the ServiceLive Site available; </li>
								<li>use the ServiceLive Site and/ or any User Content, intentionally or unintentionally, to violate any applicable local, state, federal or international law; </li>
								<li>collect or store personal data about other Users in connection with the prohibited activities described in this paragraph. </li>
								<li>engage in advertising to or solicitation of, other Users for anything other than the posting of service orders through the mechanisms provided by ServiceLive for such service order postings. This includes, but is not limited to solicitation or advertising to buy or sell products or services through the ServiceLive Site or to attend parties or other social functions or networking for commercial purposes. You may not transmit any chain letters or junk email to other Users. </li>
								<li>use any information obtained from the ServiceLive Site in order to harass, abuse or harm another person, or in order to contact, advertise to, solicit or sell to any User without their prior explicit consent.  </li>
								<li>adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Site or any software used on or for the Site or cause others to do so. </li>
							</ul>
						
						
							<h2>User Content Posted By You on the ServiceLive Site</h2>
							<p>Without limiting the generality of any other provisions of these Terms of Service, you agree:</p>
							<ul style="margin: 20px;">
								<li>You may not post, upload or transmit any User Content that (i) infringes or otherwise violates any copyright, patent, trademark, trade secret, publicity or privacy right or other proprietary right of any party, or (ii) is proprietary to a third party, without such third party's prior written consent. </li>
								<li>You understand and agree that we undertake no obligation to monitor but reserve the right to review and delete any User Content for any or no reason, including User Content that, in our sole discretion, (i) violates these Terms of Service, (ii) is offensive or illegal, or (iii) may harm, violate the rights of or threaten the safety of any User and/or any other individual or entity (iv) or threatens and/or interferes with the ServiceLive business model or reputation in the marketplace. </li>
								<li>You are solely responsible for any User Content you post, publish or display on the ServiceLive Site or transmit to Users. We reserve the right, but undertake no obligation, to monitor disputes between you and any other User, or any other entity or individual, in connection with the ServiceLive Site. You are solely responsible for the resolution of any disputes that arise between you and any other User or any other entity or individual.</li>
								<li>You will post only User Content you believe in good faith to be true and accurate, and you will not post to the ServiceLive Site any User Content that is false, inaccurate, misleading or fraudulent. </li>
								<li>By uploading User Content to the ServiceLive Site, you hereby grant, and represent and warrant that you have all rights and authority necessary to grant, (i) us  and our respective contractors and business partners, an irrevocable, perpetual, non-exclusive, royalty-free, fully sublicensable, fully paid up, worldwide license and right to use, copy, publicly perform, digitally perform, publicly display, and distribute such User Content and to prepare derivative works based on, or incorporate into other works, such User Content, with or without attribution; and (ii) subject to the restrictions set forth in these Terms of Service, all Users an irrevocable, perpetual, non-exclusive, royalty-free license and right to use such User Content for each such User's use in connection with the ServiceLive Site.   You hereby irrevocably waive and assign to us any and all so-called moral rights or "droit moral" you may have in or with respect to any User Content you post to the ServiceLive Site. </li>
								<li>The following is a partial list of the kind of User Content that is illegal and/or is prohibited on or through the ServiceLive Site. You may not post any content that: 
									<ul style="margin: 20px;">
										<li>is patently offensive to users of the ServiceLive Site, such as content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual; </li>
										<li>harasses or advocates harassment of another person; </li>
										<li>promotes illegal activities or conduct that is abusive; </li>
										<li>is threatening, obscene, defamatory or libelous; </li>
										<li>is pornographic or sexually explicit in nature; or </li>
										<li>seeks, or recommends providers of, material that exploits people under the age of 18 in a sexual or violent manner, or seeks or recommends providers that solicit personal information from anyone under 18. </li>
									</ul>
								</li>									
							</ul>
							
							
							<h2>Copyrights</h2>
							<p>If you believe any User Content or any other aspect of the ServiceLive Site infringes your copyright, you should send written notice of copyright infringement to our designated copyright agent at the address given below. Your notice must meet the requirements of the Digital Millennium Copyright Act (as required under 17 U.S.C. §512) by providing the following information: </p>
							<ol style="margin: 20px;">
								<li>A description of the copyrighted work that you claim has been infringed; </li>
								<li>A description of where the material that you claim is infringing is located on the ServiceLive Site</li>
								<li>Your address, telephone number and email address; </li>
								<li>A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; </li>
								<li>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the owner of the copyright at issue or are authorized to act on the copyright owner's behalf; and</li>
								<li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright at issue. </li>
							</ol>
							
							<p>Our designated copyright agent for notice of claims of copyright infringement on the ServiceLive Site may be reached at the following address:</p>
							
							<p><strong>Copyright Agent
							<br />Sears Holdings Management Corporation</strong>
							<br />3333 Beverly Road
							<br />Hoffman Estates, IL  60179
							</p>
							
							<p>Or by email:  shmcdmca@searshc.com</p>
							
							<h2>Privacy</h2>
							<p>Use of the ServiceLive Site is also governed by our Privacy Policy, which we encourage you to review.</p>
							
							
							<h2>Ownership</h2>
							<p>As between you and us, the ServiceLive Site, including all photographs, images, text, graphics, icons, audio clips, software and other aspects thereof (excluding User Content), all improvements or modifications thereof, all derivative works based thereon, and the collection, arrangement, and assembly of the ServiceLive Site, including all copyrights, trademarks, and other intellectual property or proprietary rights in the foregoing, are owned by us or our licensors. As between you and us, subject to any licenses and rights expressly granted herein, any User Content posted by you is owned by you. Nothing contained in these Terms of Service shall be deemed to grant to you or any other User any rights, title or interest in or to any copyright, trademark or other proprietary right of ours or any of our licensors. </p>
							<p> Any trademarks, service marks, and other marks and indicators of source or origin that are displayed on the ServiceLive Site are the proprietary property of ServiceLive or its respective licensors, as applicable. None of such marks may be used in connection with any other product or service, in any manner that is likely to cause confusion among consumers, or to disparage or discredit the owner of such mark or its affiliates. Any trademarks of third parties that appear on the ServiceLive Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by us. You may not use, copy, modify or display any of the trademarks, service marks, names or logos appearing on the ServiceLive Site without the express written permission of the trademark owner. </p>
							<p> Nothing in these Terms of Service shall be deemed to grant to you or any other User any license or right in or to any patent, copyright, trademark, trade secret or other proprietary right of ours. </p>
							
							<!-- SL-21341 changes starts -->
							<!--<h2>Disclaimer</h2>
							<p>YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICELIVE SITE, AND OF ANY USER CONTENT, INFORMATION, ADVICE, SERVICES, PRODUCTS, AND OTHER MATERIALS CONTAINED IN OR DESCRIBED ON THE SERVICELIVE SITE, IS ENTIRELY AT YOUR OWN RISK, AND THAT ALL SUCH INFORMATION AND MATERIALS ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, WE MAKE NO, AND HEREBY DISCLAIM ALL, REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE AVAILABILITY, OPERATION AND/OR USE OF THE SERVICELIVE SITE, INCLUDING BUT NOT LIMITED TO ANY USER CONTENT PROVIDED VIA THE SERVICELIVE SITE, AND ALL OTHER CONTENT, SERVICES, PRODUCTS, AND OTHER INFORMATION AND MATERIALS CONTAINED IN OR DESCRIBED ON THE SERVICELIVE SITE, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT, AND IMPLIED WARRANTIES ARISING FROM COURSE OF DEALING OR COURSE OF PERFORMANCE. IN ADDITION, WE DO NOT REPRESENT OR WARRANT THAT THE INFORMATION AND CONTENT ACCESSIBLE VIA THE SERVICELIVE SITE IS ACCURATE, COMPLETE OR CURRENT, AND WE ARE NOT RESPONSIBLE FOR ANY ERRORS OR OMISSIONS THEREIN OR FOR ANY ADVERSE CONSEQUENCES RESULTING FROM USE OF, INABILITY TO USE, OR RELIANCE ON ANY ASPECT OF THE SERVICELIVE SITE, INCLUDING BUT NOT LIMITED TO USER CONTENT AND ALL OTHER CONTENT, SERVICES, PRODUCTS, AND OTHER INFORMATION AND MATERIALS CONTAINED IN OR DESCRIBED ON THE SERVICELIVE SITE. FURTHER, WE MAKE NO REPRESENTATIONS AND WARRANTIES THAT THE SERVICELIVE SITE OR THE USER CONTENT WILL BE UNINTERRUPTED, SECURE, OR FREE OF ERRORS, VIRUSES, OR OTHER HARMFUL COMPONENTS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY ANY USER FROM US OR THE SERVICELIVE SITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. </p>
							
							<h2>Limitation on Liability</h2>
							<p>IN NO EVENT SHALL SERVICELIVE OR ITS RESPECTIVE AFFILIATES, OR THE SHAREHOLDERS, DIRECTORS, OFFICERS, MEMBERS, MANAGERS, EMPLOYEES, AGENTS OR REPRESENTATIVES OF ANY OF THE FOREGOING, BE LIABLE TO YOU OR ANY THIRD PARTY FOR DAMAGES OF ANY KIND (INCLUDING, BUT NOT LIMITED TO, ANY DIRECT, INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OR DAMAGES FOR LOSS OF PROFITS, GOODWILL OR REVENUE, BUSINESS INTERRUPTION, OR LOSS OF DATA) ARISING OUT OF THE USE OF, ACCESS TO, RELIANCE ON, UNAVAILABILITY OF, INABILITY TO USE OR IMPROPER USE OF THE SERVICELIVE SITE, INCLUDING BUT NOT LIMITED TO ANY USER CONTENT, REVIEWS, ADVICE, SERVICES, PRODUCTS, AND OTHER INFORMATION AND MATERIALS CONTAINED IN OR DESCRIBED ON THE SERVICELIVE SITE, OR THE DISCLOSURE OR MISUSE OF ANY USER'S PERSONAL INFORMATION, EVEN IF THEY HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, OR OTHERWISE. IN ANY EVENT, SERVICELIVE'S RESPECTIVE TOTAL MAXIMUM LIABILITY IN RESPECT OF THE SERVICELIVE SITE OR ANY PART THEREOF, INCLUDING BUT NOT LIMITED TO THE USER CONTENT, REVIEWS, ADVICE, SERVICES, PRODUCTS, AND OTHER INFORMATION AND MATERIALS CONTAINED IN OR DESCRIBED ON THE SERVICELIVE SITE, IN ANY MANNER WHATSOEVER, SHALL BE LIMITED TO ONE HUNDRED UNITED STATES DOLLARS ($100.00). THIS LIMITATION SHALL APPLY NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF ANY LIMITED REMEDY PROVIDED HEREIN. </p>
							
							<h2>Indemnity</h2>
							<p>You agree to indemnify and hold ServiceLive and its respective affiliates, licensors, directors, officers, members, managers, employees, agents, and representatives, harmless from and against any losses, costs, expenses or damages of any nature whatsoever (including attorneys fees and court costs) arising from any claim, cause of action, suit or demand of any third party due to, arising out of or related to (i) your access to the ServiceLive Site, (ii) your use of the ServiceLive Site, (iii) any User Content posted, uploaded or transmitted by you, (iv) your use or distribution of any User Content, (v) your violation of these Terms of Service, (vi) any use of your User ID or password by you or any third party, or (vii) the infringement or other violation by you, or any third party using your account or User ID or password, of any intellectual property or other right of any person or entity. </p>
							
							-->
								<!-- SL-21341 changes ends -->
							
							<h2>Third Party Advertisements and Links to Third Party Sites</h2>
							<p>We may display on the ServiceLive Site advertisements from third parties, such as banner advertisements and pop-up texts, and links to third party sites. We are not responsible for the content of such advertisements or links, any products, services or other materials relating to such advertisements, any linked site, or any link contained in a linked site. The display of any advertisement or link does not imply endorsement by us of the advertisement or linked site or any content therein. IN NO EVENT WILL WE BE LIABLE, DIRECTLY OR INDIRECTLY, TO ANYONE FOR ANY DAMAGE OR LOSS ARISING FROM OR RELATING TO ANY USE, CONTINUED USE OR RELIANCE ON ANY ADVERTISEMENT DISPLAYED ON THE SERVICELIVE SITE, ANY PRODUCTS, SERVICES OR OTHER MATERIALS RELATING TO ANY SUCH ADVERTISEMENT, ANY LINKED THIRD-PARTY SITE, OR ANY LINK CONTAINED IN A LINKED SITE.</p>
							
							<h2>Changes to Terms of Service</h2>
							<p>We reserve the right to make changes at any time to these terms of Service. Any modifications to the Terms of Service will be effective upon posting. You agree to review the Terms of Service periodically so that you are aware of any modifications. Your continued use of the ServiceLive Site after any modifications indicates your acceptance of the modified Terms of Service.</p>
							
							<h3>Disputes</h3>
							<p>Any dispute relative to the ServiceLive Site or use or inability to use the ServiceLive Site will be governed by the laws of the State of Illinois, without regard to its conflict of law provisions.  Any dispute relating in any way to your visit to or participation on the ServiceLive Site shall be submitted to confidential arbitration in Chicago, Illinois, except that, to the extent you have in any manner violated or threatened to violate our intellectual property rights, we may seek injunctive or other appropriate relief in any state or federal court in the State of Illinois, and you consent to exclusive jurisdiction and venue in such courts. You understand and agree that you are waiving your right to sue or go to court to assert or defend your rights under this contract. Arbitration under these Terms of Service shall be conducted under the rules then prevailing of the American Arbitration Association.  The arbitrator's award shall be binding and may be entered as a judgment in any court of competent jurisdiction.  To the fullest extent permitted by applicable law, no arbitration under these Terms of Service shall be joined to an arbitration involving any other party subject to this Agreement, whether through class arbitration involving any other party subject to these Terms of Service, whether through class arbitration proceedings or otherwise. </p>
							
							<h3>Applicable law</h3>
							<p>By visiting ServiceLive Site, you agree that the laws of the State of Illinois, without regard to principles of conflict of laws, will govern these Terms of Service and any dispute of any sort that might arise between you and ServiceLive Site. </p>
							
							<h3>Miscellaneous</h3>
							<p>No agency, partnership, joint venture, or employment relationship is created as a result of these Terms of Service, and you do not have any authority of any kind to bind ServiceLive in any respect whatsoever. We may provide you with notices, including those regarding changes to these Terms of Service, by email, regular mail, or postings on the ServiceLive Site. These Terms of Service, together with the Privacy Policy, the Buyer Agreement (for Users registered as Buyers), and the Provider Agreement (for Users registered as Providers) constitute the entire agreement among you and ServiceLive regarding use of the ServiceLive Site.   ServiceLive's failure to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of the enforcement of such right or provision. If any provision of these Terms of Service is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms of Service shall otherwise remain in full force and effect and enforceable. These Terms of Service are not assignable, transferable or sublicensable by you, except with our prior written consent. The headings in these Terms of Service are for convenience only and have no legal or contractual effect. These Terms of Service include and incorporate the Privacy Policy for the ServiceLive Site and any notices regarding the ServiceLive Site.</p>
							
							<h3>Contact and Violations</h3>
							<p>Please contact us with any questions regarding these Terms of Service.  Please report any violations of the Terms of Service to support@ServiceLive.com.</p>
							
							
							<!-- SL-21341 changes starts -->
							<!--<p style="font-weight: bold;">Effective Date: November 6, 2008</p>
							--><p style="font-weight: bold;">Effective Date: August, 2016</p>
							<!-- SL-21341 changes ends -->

					</div>
				</div>
				<div class="clear"></div>
			</div>
			<!-- START FOOTER -->
			<jsp:include page="/jsp/public/common/defaultFooter.jsp" />
			<!-- END FOOTER -->
		</div>
	</body>
</html>
