/**
 * 
 */
package com.servicelive.domain.common;


/**
 * @author hoza
 *
 */
public enum BuyerFeatureSetEnum {
	 ORDER_GROUPING ,
	 ASSURANT_ALERTS,
	 AUTO_ROUTE,
	 SHC_GL_REPORTING,
	 SKU_DETAILS_FROM_SST,
	 SUBSTATUS_ALERTS,
	 TIER_ROUTE,
	 UPDATE_SO_DESCRIPTIONS,
	 WS_UPDATE_PARTS,
	 WS_UPDATE_SCHEDULE,
	 CONDITIONAL_ROUTE,
     HSR_ALERTS,
     ALLOW_BID_ORDERS,
     ALLOW_SEALED_BID_ORDERS,
     NEW_ORDER_ON_CLOSE_ORDER_UPDATE,
     UPDATE_CLOSE_ORDER,
     TASK_LEVEL,
     AUTO_CLOSE,
     SCOPE_CHANGE,
     MARKETPLACE_PROVIDER_SEARCH_OFF,
     AUTO_POST_API_SO,
     TRIP_CHARGE_OVERRIDE,
     VALIDATE_TIME_ONSITE,
     MARKET_ADJUSTMENT_RATE,
     SO_CREATION_SKU,
     AUTO_ACCEPTANCE,
     LEAD_MANAGEMENT,
     NON_FUNDED,
     NOTES_FEATURE,
     BACKGROUND_CHECK_RECERTIFICATION,
     INHOME_AUTO_CLOSE,
	 NONE,
	 LABOR_PRICE_REDUCTION,
	 DISABLE_CONFLICT_FINDER,
	 ALLOW_SKU_TAX,
	 UNIQUE_ORDER,
	 CONSUMER_EMAIL,
	 CONSUMER_SURVEY;
}
