{ items: [
	{
	  "large":"../../../images/support/tut2_step1.gif"
	},
	{
	  "large":"../../../images/support/tut2_step2.gif"
	},
	{
	  "large":"../../../images/support/tut2_step3.gif"
	},
	{	 
	  "large":"../../../images/support/tut2_step4.gif"
	},
	{
	  "large":"../../../images/support/tut2_step5.gif"
	},
	{
	  "large":"../../../images/support/tut2_step6.gif"
	},
	{
	  "large":"../../../images/support/tut2_step7.gif"
	},
	{
	  "large":"../../../images/support/tut2_step8.gif"
	},
	{
	  "large":"../../../images/support/tut2_step9.gif"
	}
	//
]}